export interface CompanySlide {
  title: string;
  content: string;
  highlight?: string;
  type?: "insight" | "competitive" | "investment";
}

export interface Company {
  id: string;
  name: string;
  ticker?: string;
  logo: string;
  description: string;
  ceo: string;
  founded: string;
  headquarters: string;
  employees: string;
  marketCap?: string;
  keyProducts: string[];
  recentNews?: string;
  segment: "commercial" | "defense" | "space" | "propulsion" | "suppliers" | "services";
  industryRole: string;
  slides: CompanySlide[];
  keyStats?: {
    label: string;
    value: string;
  }[];
  competitors?: string[];
}

export interface MarketCompanies {
  [marketId: string]: Company[];
}

export const marketCompanies: MarketCompanies = {
  aerospace: [
    // === COMMERCIAL AVIATION ===
    {
      id: "boeing",
      name: "Boeing",
      ticker: "BA",
      logo: "✈️",
      segment: "commercial",
      description: "The world's largest aerospace company and leading manufacturer of commercial jetliners, defense, space and security systems.",
      industryRole: "Boeing is one of two major commercial aircraft manufacturers globally (duopoly with Airbus). They define industry standards for wide-body aircraft and have massive influence on supply chains.",
      ceo: "Kelly Ortberg",
      founded: "1916",
      headquarters: "Arlington, Virginia",
      employees: "170,000+",
      marketCap: "$120B+",
      keyProducts: ["737 MAX", "787 Dreamliner", "777X", "Defense & Space"],
      recentNews: "Focus on safety improvements and production ramp-up of 737 MAX",
      slides: [
        { title: "Industry Giant", content: "Boeing commands ~40% of the global commercial aircraft market, delivering 500+ aircraft annually. Their backlog exceeds $500B.", highlight: "$500B+ backlog", type: "insight" },
        { title: "Vertical Integration", content: "Unlike Airbus, Boeing owns more of its supply chain, from fuselages to avionics. This gives them control but also concentration risk.", highlight: "Vertically integrated", type: "insight" },
        { title: "Defense Pillar", content: "Boeing's defense segment generates ~40% of revenue, providing stability during commercial downturns. Key programs include F-15EX and KC-46 tanker.", highlight: "40% defense revenue", type: "insight" },
        { title: "Space Ambitions", content: "Through Starliner and Space Launch System (SLS), Boeing is NASA's primary commercial crew partner alongside SpaceX.", highlight: "NASA partner", type: "insight" },
        { title: "Competitive Position", content: "Boeing trails Airbus in orders but dominates wide-body with 787/777. Quality issues have eroded trust. Main threats: Airbus execution, COMAC long-term.", highlight: "Wide-body leader", type: "competitive" },
        { title: "Investment Thesis", content: "Turnaround play with new CEO. Massive backlog provides visibility. Key risks: quality execution, MAX reputation, defense cost overruns. Buy on stabilization.", highlight: "Turnaround story", type: "investment" },
      ],
      keyStats: [
        { label: "Aircraft Delivered (2024)", value: "528" },
        { label: "Order Backlog", value: "5,600+" },
        { label: "Revenue", value: "$77.8B" },
      ],
      competitors: ["Airbus", "Embraer", "COMAC"],
    },
    {
      id: "airbus",
      name: "Airbus",
      ticker: "AIR.PA",
      logo: "🌐",
      segment: "commercial",
      description: "European multinational aerospace corporation and one of the world's largest aircraft manufacturers.",
      industryRole: "Airbus is Boeing's only true competitor in large commercial aircraft. They've captured market share through the fuel-efficient A320neo family and have a stronger order book.",
      ceo: "Guillaume Faury",
      founded: "1970",
      headquarters: "Leiden, Netherlands",
      employees: "130,000+",
      marketCap: "$150B+",
      keyProducts: ["A320neo", "A350", "A380", "Helicopters"],
      recentNews: "Record deliveries and strong order backlog exceeding 8,000 aircraft",
      slides: [
        { title: "Market Leader", content: "Airbus delivered 735 aircraft in 2023, outselling Boeing. Their A320neo family dominates the single-aisle segment with 60%+ market share.", highlight: "735 deliveries in 2023", type: "insight" },
        { title: "European Champion", content: "Backed by France, Germany, Spain, and UK governments, Airbus represents European aerospace sovereignty and employs 130,000+ across the continent.", highlight: "Pan-European", type: "insight" },
        { title: "Innovation Focus", content: "Leading the ZEROe hydrogen aircraft initiative, targeting zero-emission commercial flight by 2035. Also investing heavily in sustainable aviation fuels.", highlight: "Hydrogen by 2035", type: "insight" },
        { title: "Helicopter Dominance", content: "Airbus Helicopters is the world's largest civil and parapublic helicopter manufacturer with 50%+ market share.", highlight: "#1 in helicopters", type: "insight" },
        { title: "Competitive Position", content: "Winning the single-aisle war with A320neo. Boeing's troubles gift market share. Risks: supply chain constraints, engine availability limiting production ramp.", highlight: "Single-aisle winner", type: "competitive" },
        { title: "Investment Thesis", content: "Premium aerospace franchise with pricing power. Decade of deliveries locked in. Trade at premium to Boeing for good reason. Best pure-play on aviation recovery.", highlight: "Quality compounder", type: "investment" },
      ],
      keyStats: [
        { label: "Aircraft Delivered (2023)", value: "735" },
        { label: "Order Backlog", value: "8,600+" },
        { label: "Revenue", value: "€65.4B" },
      ],
      competitors: ["Boeing", "COMAC", "Embraer"],
    },
    {
      id: "embraer",
      name: "Embraer",
      ticker: "ERJ",
      logo: "🇧🇷",
      segment: "commercial",
      description: "Brazilian aerospace company specializing in regional jets and executive aviation.",
      industryRole: "Embraer dominates the regional jet market (70-150 seats) where Boeing and Airbus don't compete directly. They're the third-largest aircraft manufacturer globally.",
      ceo: "Francisco Gomes Neto",
      founded: "1969",
      headquarters: "São José dos Campos, Brazil",
      employees: "19,000+",
      marketCap: "$7B+",
      keyProducts: ["E-Jet E2", "Phenom", "Praetor", "KC-390"],
      recentNews: "E2 family gaining orders as airlines seek right-sized aircraft",
      slides: [
        { title: "Regional King", content: "Embraer controls ~60% of the regional jet market with its E-Jet family. Airlines choose them when 737/A320 capacity is too large.", highlight: "60% regional market", type: "insight" },
        { title: "Executive Jets", content: "Their Phenom and Praetor lines compete with Bombardier and Gulfstream in the lucrative business jet segment.", highlight: "Business aviation", type: "insight" },
        { title: "Defense Export", content: "The KC-390 military transport is gaining traction as a C-130 alternative, with orders from Portugal, Hungary, and Netherlands.", highlight: "KC-390 exports", type: "insight" },
        { title: "Failed Boeing Deal", content: "A 2020 merger with Boeing's commercial division collapsed, leaving Embraer independent but stronger, now exploring partnerships.", highlight: "Independent survivor", type: "insight" },
        { title: "Competitive Position", content: "Owns the regional niche Boeing/Airbus abandoned. Bombardier exit strengthens position. Threat: airlines up-gauging to A220/MAX.", highlight: "Niche dominance", type: "competitive" },
        { title: "Investment Thesis", content: "Undervalued relative to peers. E2 cycle ramping. Defense exports diversify. Potential M&A target. Brazilian currency adds volatility.", highlight: "Undervalued niche", type: "investment" },
      ],
      keyStats: [
        { label: "Aircraft Delivered (2023)", value: "181" },
        { label: "Backlog Value", value: "$21B" },
        { label: "Revenue", value: "$5.3B" },
      ],
      competitors: ["Bombardier", "ATR", "Mitsubishi"],
    },
    // === DEFENSE ===
    {
      id: "lockheed",
      name: "Lockheed Martin",
      ticker: "LMT",
      logo: "🛡️",
      segment: "defense",
      description: "Global security and aerospace company focused on defense, space, and advanced technology systems.",
      industryRole: "The world's largest defense contractor. Lockheed sets the standard for 5th-generation fighters and is the prime contractor for critical national security programs.",
      ceo: "Jim Taiclet",
      founded: "1995 (merger)",
      headquarters: "Bethesda, Maryland",
      employees: "116,000+",
      marketCap: "$140B+",
      keyProducts: ["F-35 Lightning II", "C-130 Hercules", "Missiles & Fire Control", "Sikorsky Helicopters"],
      recentNews: "F-35 production ramping to 156 jets/year, massive international demand",
      slides: [
        { title: "Defense Titan", content: "Lockheed receives more U.S. defense dollars than any other company—$75B+ annually. The F-35 alone is a $1.7 trillion lifetime program.", highlight: "$1.7T F-35 program", type: "insight" },
        { title: "F-35 Dominance", content: "The F-35 is the backbone of Western air power, with 900+ delivered to 18 nations. It's the most expensive weapon system in history.", highlight: "900+ F-35s delivered", type: "insight" },
        { title: "Space Systems", content: "Lockheed builds GPS satellites, missile warning systems, and the Orion spacecraft for NASA's Artemis moon missions.", highlight: "Artemis partner", type: "insight" },
        { title: "Hypersonic Race", content: "Leading U.S. hypersonic weapons development with programs like ARRW and Dark Eagle, competing with China and Russia.", highlight: "Hypersonic leader", type: "insight" },
        { title: "Competitive Position", content: "Unassailable in 5th-gen fighters. F-35 lock-in creates 50+ year revenue stream. Northrop and RTX compete in missiles/space but not aircraft.", highlight: "Fighter monopoly", type: "competitive" },
        { title: "Investment Thesis", content: "Defense budget tailwinds for decade. F-35 annuity business. 3% dividend yield. Low beta hedge. Limited upside but sleep-well-at-night defense.", highlight: "Defense bond", type: "investment" },
      ],
      keyStats: [
        { label: "Revenue (2023)", value: "$67.6B" },
        { label: "Backlog", value: "$160B+" },
        { label: "F-35 Delivered", value: "950+" },
      ],
      competitors: ["Northrop Grumman", "Raytheon", "Boeing Defense"],
    },
    {
      id: "northrop",
      name: "Northrop Grumman",
      ticker: "NOC",
      logo: "🦅",
      segment: "defense",
      description: "Global aerospace and defense technology company known for stealth aircraft and space systems.",
      industryRole: "Northrop is the stealth technology leader, building America's most advanced bombers and unmanned systems. They're essential to nuclear deterrence.",
      ceo: "Kathy Warden",
      founded: "1994 (merger)",
      headquarters: "Falls Church, Virginia",
      employees: "95,000+",
      marketCap: "$80B+",
      keyProducts: ["B-21 Raider", "James Webb Telescope", "Global Hawk", "Sentinel ICBM"],
      recentNews: "B-21 Raider stealth bomber unveiled, production ramping up",
      slides: [
        { title: "Stealth Pioneer", content: "Northrop built the B-2 Spirit and now the B-21 Raider—the world's most advanced stealth bombers. Only they have this capability.", highlight: "Only B-21 maker", type: "insight" },
        { title: "Nuclear Triad", content: "Building the Sentinel ICBM to replace Minuteman III, a $100B+ program ensuring U.S. nuclear deterrence for decades.", highlight: "$100B Sentinel", type: "insight" },
        { title: "Space Excellence", content: "Built the James Webb Space Telescope and key components for national security satellites. Space revenue is ~25% of total.", highlight: "James Webb builder", type: "insight" },
        { title: "Autonomous Systems", content: "Global Hawk drones have flown 500,000+ hours. MQ-4C Triton expands Navy surveillance capabilities globally.", highlight: "500K+ drone hours", type: "insight" },
        { title: "Competitive Position", content: "Sole-source on B-21 and Sentinel—crown jewels. Competes with Lockheed on space, RTX on missiles. Moat in stealth unmatched.", highlight: "Stealth monopoly", type: "competitive" },
        { title: "Investment Thesis", content: "Highest-quality defense franchise. B-21 and Sentinel provide 30+ year visibility. Premium valuation deserved. Add on pullbacks.", highlight: "Premium defense", type: "investment" },
      ],
      keyStats: [
        { label: "Revenue (2023)", value: "$39.3B" },
        { label: "Backlog", value: "$84B+" },
        { label: "Employees", value: "95,000" },
      ],
      competitors: ["Lockheed Martin", "Boeing", "General Atomics"],
    },
    {
      id: "raytheon",
      name: "RTX (Raytheon)",
      ticker: "RTX",
      logo: "🎯",
      segment: "defense",
      description: "Aerospace and defense conglomerate formed from Raytheon and United Technologies merger.",
      industryRole: "RTX is the missiles and sensors powerhouse. When a military needs precision-guided weapons or advanced radar, Raytheon is often the only option.",
      ceo: "Chris Calio",
      founded: "2020 (merger)",
      headquarters: "Arlington, Virginia",
      employees: "180,000+",
      marketCap: "$150B+",
      keyProducts: ["Patriot Missiles", "Stinger", "Pratt & Whitney Engines", "Collins Aerospace"],
      recentNews: "Massive demand for Patriot systems and Stinger missiles due to Ukraine conflict",
      slides: [
        { title: "Merged Giant", content: "2020 merger of Raytheon (missiles) and United Technologies (Pratt engines, Collins avionics) created a $70B+ revenue powerhouse.", highlight: "$70B+ revenue", type: "insight" },
        { title: "Missile Monopoly", content: "Raytheon makes Patriot, Stinger, Tomahawk, and AMRAAM missiles. Ukraine conflict depleted inventories, creating years of backlog.", highlight: "Ukraine surge", type: "insight" },
        { title: "Engine Empire", content: "Pratt & Whitney powers 25% of commercial aircraft (A320neo, 787) and 100% of F-35s. A critical strategic asset.", highlight: "25% of aircraft", type: "insight" },
        { title: "Avionics Leader", content: "Collins Aerospace supplies cockpits, sensors, and systems to virtually every major aircraft program globally.", highlight: "Universal supplier", type: "insight" },
        { title: "Competitive Position", content: "Only Lockheed competes broadly. Pratt duopoly with GE. Collins near-monopoly on avionics. GTF engine issues temporary headwind.", highlight: "Diversified leader", type: "competitive" },
        { title: "Investment Thesis", content: "Best balance of defense + commercial. Ukraine restocking drives missiles. Pratt issues priced in. Dividend aristocrat. Core holding.", highlight: "Balanced exposure", type: "investment" },
      ],
      keyStats: [
        { label: "Revenue (2023)", value: "$68.9B" },
        { label: "Backlog", value: "$196B" },
        { label: "Employees", value: "180,000" },
      ],
      competitors: ["Lockheed Martin", "Northrop Grumman", "L3Harris"],
    },
    {
      id: "gd",
      name: "General Dynamics",
      ticker: "GD",
      logo: "⚓",
      segment: "defense",
      description: "Diversified defense company spanning submarines, land systems, IT, and business jets.",
      industryRole: "General Dynamics builds America's nuclear submarines and main battle tanks—the backbone of naval and ground deterrence. Also owns Gulfstream.",
      ceo: "Phebe Novakovic",
      founded: "1952",
      headquarters: "Reston, Virginia",
      employees: "106,000+",
      marketCap: "$75B+",
      keyProducts: ["Virginia-class Submarines", "Abrams Tank", "Gulfstream Jets", "IT Services"],
      recentNews: "Columbia-class submarine program critical to nuclear deterrence",
      slides: [
        { title: "Submarine Maker", content: "Electric Boat division is one of only two U.S. submarine builders. Columbia-class boomers are a $130B program for nuclear deterrence.", highlight: "$130B submarine program", type: "insight" },
        { title: "Ground Combat", content: "The M1 Abrams tank remains the West's premier main battle tank. Stryker vehicles provide Army mobility globally.", highlight: "Abrams dominance", type: "insight" },
        { title: "Gulfstream Luxury", content: "Gulfstream business jets ($50M-$75M each) generate high margins and consistent cash flow, insulating from defense cycles.", highlight: "High-margin jets", type: "insight" },
        { title: "IT Giant", content: "GDIT provides cloud, cyber, and AI services to U.S. government agencies—a stable, growing $10B+ business.", highlight: "$10B+ IT services", type: "insight" },
        { title: "Competitive Position", content: "Duopoly in subs with Huntington Ingalls. Only Abrams maker. Gulfstream competes with Bombardier/Dassault at top end.", highlight: "Irreplaceable assets", type: "competitive" },
        { title: "Investment Thesis", content: "Most diversified defense name. Gulfstream cycle turning up. Submarine demand locked in. Consistent capital returns. Steady compounder.", highlight: "Diversified compounder", type: "investment" },
      ],
      keyStats: [
        { label: "Revenue (2023)", value: "$42.3B" },
        { label: "Backlog", value: "$93B+" },
        { label: "Gulfstream Deliveries", value: "152" },
      ],
      competitors: ["Huntington Ingalls", "BAE Systems", "Textron"],
    },
    {
      id: "l3harris",
      name: "L3Harris",
      ticker: "LHX",
      logo: "📡",
      segment: "defense",
      description: "Defense technology company specializing in communications, electronic warfare, and sensors.",
      industryRole: "L3Harris is the communications and electronic warfare specialist. They connect military forces globally and provide critical ISR capabilities.",
      ceo: "Chris Kubasik",
      founded: "2019 (merger)",
      headquarters: "Melbourne, Florida",
      employees: "50,000+",
      marketCap: "$45B+",
      keyProducts: ["Tactical Radios", "Electronic Warfare", "ISR Systems", "Space & Airborne"],
      recentNews: "Acquiring Aerojet Rocketdyne to add propulsion capabilities",
      slides: [
        { title: "Comms Backbone", content: "L3Harris radios connect U.S. and allied forces worldwide. Their AN/PRC-163 is the next-gen soldier radio.", highlight: "Next-gen radios", type: "insight" },
        { title: "Electronic Warfare", content: "Critical for jamming enemy radar and communications. EW capabilities are essential in modern peer conflicts.", highlight: "EW specialist", type: "insight" },
        { title: "Aerojet Acquisition", content: "Acquiring Aerojet Rocketdyne for $4.7B adds missile propulsion, creating a more vertically integrated defense prime.", highlight: "$4.7B acquisition", type: "insight" },
        { title: "Space Focus", content: "Building resilient space systems for missile tracking and communications that can survive adversary attacks.", highlight: "Resilient space", type: "insight" },
        { title: "Competitive Position", content: "Competes with RTX on sensors, Northrop on space. Radio franchise unmatched. Aerojet deal adds propulsion moat.", highlight: "Radio leader", type: "competitive" },
        { title: "Investment Thesis", content: "Growth-ier defense name. EW and space are hot areas. Aerojet integration risk. Smaller scale than mega-primes. Higher beta.", highlight: "Growth defense", type: "investment" },
      ],
      keyStats: [
        { label: "Revenue (2023)", value: "$19.4B" },
        { label: "Backlog", value: "$32B" },
        { label: "Employees", value: "50,000" },
      ],
      competitors: ["RTX", "Northrop Grumman", "BAE Systems"],
    },
    {
      id: "bae",
      name: "BAE Systems",
      ticker: "BA.L",
      logo: "🇬🇧",
      segment: "defense",
      description: "British multinational defense and aerospace company, Europe's largest defense contractor.",
      industryRole: "BAE is the UK's defense champion and a key partner for U.S. programs. They're essential to European and Five Eyes security architecture.",
      ceo: "Charles Woodburn",
      founded: "1999 (merger)",
      headquarters: "London, UK",
      employees: "100,000+",
      marketCap: "$50B+",
      keyProducts: ["Typhoon Fighter", "Astute Submarines", "Electronic Systems", "M777 Howitzer"],
      recentNews: "Major beneficiary of European defense spending surge post-Ukraine",
      slides: [
        { title: "Transatlantic Power", content: "45% of BAE revenue comes from the U.S., where they're a major defense contractor. True Five Eyes integration.", highlight: "45% U.S. revenue", type: "insight" },
        { title: "Typhoon Program", content: "Lead partner on Eurofighter Typhoon, competing with F-35 for European orders. 600+ delivered.", highlight: "Typhoon leader", type: "insight" },
        { title: "AUKUS Partner", content: "Central to AUKUS submarine deal, helping Australia build nuclear-powered subs—a generational $368B program.", highlight: "AUKUS critical", type: "insight" },
        { title: "Land Systems", content: "Major artillery and armored vehicle provider to U.S. Army and allies. M777 howitzer used extensively in Ukraine.", highlight: "M777 in Ukraine", type: "insight" },
        { title: "Competitive Position", content: "UK national champion with transatlantic reach. Competes with U.S. primes but often partners. AUKUS is unique advantage.", highlight: "UK champion", type: "competitive" },
        { title: "Investment Thesis", content: "Best European defense play. GBP-denominated. European rearmament tailwind for decade. AUKUS optionality. Value vs U.S. peers.", highlight: "Europe defense play", type: "investment" },
      ],
      keyStats: [
        { label: "Revenue (2023)", value: "£25.3B" },
        { label: "Backlog", value: "£74B" },
        { label: "Countries Served", value: "40+" },
      ],
      competitors: ["Lockheed Martin", "Leonardo", "Thales"],
    },
    // === SPACE ===
    {
      id: "spacex",
      name: "SpaceX",
      logo: "⭐",
      segment: "space",
      description: "Private aerospace manufacturer and space transportation company revolutionizing access to space.",
      industryRole: "SpaceX has fundamentally disrupted launch services with reusable rockets, reducing costs 10x. They now launch more than all other providers combined.",
      ceo: "Elon Musk",
      founded: "2002",
      headquarters: "Hawthorne, California",
      employees: "13,000+",
      marketCap: "$200B+ (private)",
      keyProducts: ["Falcon 9", "Starship", "Starlink", "Dragon"],
      recentNews: "Starship development accelerating, Starlink approaching 6,000 satellites",
      slides: [
        { title: "Launch Dominance", content: "SpaceX launched 96 rockets in 2023—more than the rest of the world combined. Falcon 9 is the most reliable rocket in history.", highlight: "96 launches in 2023", type: "insight" },
        { title: "Reusability Revolution", content: "Falcon 9 boosters have landed 250+ times and flown 20+ missions each. This slashed launch costs from $200M to under $70M.", highlight: "250+ landings", type: "insight" },
        { title: "Starlink Empire", content: "5,500+ satellites provide global internet. $6B+ annual revenue, profitable, and funding Starship development.", highlight: "$6B+ Starlink revenue", type: "insight" },
        { title: "Starship Vision", content: "Fully reusable Starship aims for $10M per launch—enabling Mars colonization and point-to-point Earth travel.", highlight: "$10M per launch goal", type: "insight" },
        { title: "Competitive Position", content: "No true competitor in launch tempo or cost. ULA, Ariane, China are years behind. Starlink faces Amazon Kuiper. Key-man risk with Musk.", highlight: "Unmatched lead", type: "competitive" },
        { title: "Investment Thesis", content: "Private. Secondary shares at $200B+ valuation. Starlink could IPO separately. Transformational company but rich valuation and Musk risk.", highlight: "Private, pricey", type: "investment" },
      ],
      keyStats: [
        { label: "Launches (2024)", value: "130+" },
        { label: "Starlink Sats", value: "6,000+" },
        { label: "Valuation", value: "$200B+" },
      ],
      competitors: ["ULA", "Rocket Lab", "Blue Origin"],
    },
    {
      id: "blue-origin",
      name: "Blue Origin",
      logo: "🪶",
      segment: "space",
      description: "Jeff Bezos' space company focused on reusable launch vehicles and lunar infrastructure.",
      industryRole: "Blue Origin is developing New Glenn to compete with Falcon 9 and leading the Artemis lunar lander program. Well-funded but execution-challenged.",
      ceo: "Dave Limp",
      founded: "2000",
      headquarters: "Kent, Washington",
      employees: "10,000+",
      marketCap: "$15B+ (private)",
      keyProducts: ["New Shepard", "New Glenn", "Blue Moon Lander", "BE-4 Engine"],
      recentNews: "New Glenn first launch imminent, BE-4 engines powering Vulcan",
      slides: [
        { title: "Gradatim Ferociter", content: "Blue Origin's motto means 'Step by Step, Ferociously.' Unlike SpaceX's move-fast approach, they prioritize methodical development.", highlight: "Methodical approach", type: "insight" },
        { title: "New Glenn Coming", content: "New Glenn is a heavy-lift rocket with reusable first stage, targeting Falcon Heavy competition. First launch expected 2024.", highlight: "Heavy-lift competitor", type: "insight" },
        { title: "Artemis Partner", content: "Blue Origin leads the National Team for Artemis lunar landers—a $3.4B contract competing with SpaceX's Starship.", highlight: "$3.4B lunar contract", type: "insight" },
        { title: "BE-4 Milestone", content: "BE-4 engines power both New Glenn and ULA's Vulcan rocket, making Blue Origin a critical propulsion supplier.", highlight: "Engine supplier", type: "insight" },
        { title: "Competitive Position", content: "Years behind SpaceX in launch cadence. Bezos funding removes capital constraints. Execution track record is main question mark.", highlight: "Funded but slow", type: "competitive" },
        { title: "Investment Thesis", content: "Private. Bezos personal project—unclear if ever public. BE-4 engine sales provide some revenue. Speculative long-term play.", highlight: "Bezos project", type: "investment" },
      ],
      keyStats: [
        { label: "Bezos Investment", value: "$10B+" },
        { label: "Employees", value: "10,000+" },
        { label: "New Shepard Flights", value: "25+" },
      ],
      competitors: ["SpaceX", "ULA", "Relativity Space"],
    },
    {
      id: "rocket-lab",
      name: "Rocket Lab",
      ticker: "RKLB",
      logo: "🔴",
      segment: "space",
      description: "Small satellite launch and space systems company, second most frequently launched U.S. rocket.",
      industryRole: "Rocket Lab dominates small satellite launch with Electron and is developing Neutron for medium-lift. They're vertically integrated with spacecraft manufacturing.",
      ceo: "Peter Beck",
      founded: "2006",
      headquarters: "Long Beach, California",
      employees: "2,000+",
      marketCap: "$8B+",
      keyProducts: ["Electron Rocket", "Neutron Rocket", "Photon Spacecraft", "Space Systems"],
      recentNews: "Neutron medium-lift rocket development progressing, targeting 2025 launch",
      slides: [
        { title: "Small Sat Leader", content: "Electron is the second most frequently launched U.S. rocket after Falcon 9. 50+ successful missions at ~$7.5M each.", highlight: "50+ Electron launches", type: "insight" },
        { title: "Neutron Ambitions", content: "Neutron is an 8-ton reusable rocket targeting rideshare and constellation markets—directly competing with Falcon 9.", highlight: "Falcon 9 competitor", type: "insight" },
        { title: "Vertical Integration", content: "Rocket Lab builds its own engines, structures, avionics, and spacecraft. This control enables faster iteration.", highlight: "Fully integrated", type: "insight" },
        { title: "Space Systems Growth", content: "Photon spacecraft and components business growing faster than launch. Building satellites for NASA and commercial customers.", highlight: "Beyond launch", type: "insight" },
        { title: "Competitive Position", content: "Electron unmatched for dedicated small-sat. Neutron vs Falcon 9 is uphill battle. Space systems is differentiation.", highlight: "Unique positioning", type: "competitive" },
        { title: "Investment Thesis", content: "Only pure-play public space company of scale. Neutron is make-or-break. Peter Beck is exceptional founder. High risk, high reward.", highlight: "High beta space", type: "investment" },
      ],
      keyStats: [
        { label: "Electron Launches", value: "55+" },
        { label: "Revenue (2023)", value: "$245M" },
        { label: "Backlog", value: "$1.1B" },
      ],
      competitors: ["SpaceX", "Firefly", "ABL Space"],
    },
    {
      id: "ula",
      name: "United Launch Alliance",
      logo: "🚀",
      segment: "space",
      description: "Joint venture of Boeing and Lockheed Martin for national security and NASA launches.",
      industryRole: "ULA is the trusted workhorse for national security missions requiring 100% reliability. They're transitioning from Atlas/Delta to Vulcan Centaur.",
      ceo: "Tory Bruno",
      founded: "2006",
      headquarters: "Centennial, Colorado",
      employees: "3,500+",
      marketCap: "Private (JV)",
      keyProducts: ["Vulcan Centaur", "Atlas V", "Delta IV Heavy"],
      recentNews: "Vulcan Centaur certified for national security missions after successful debut",
      slides: [
        { title: "100% Success", content: "ULA has never lost a primary payload in 150+ missions. This perfect record makes them essential for irreplaceable national security satellites.", highlight: "150+ perfect missions", type: "insight" },
        { title: "Vulcan Transition", content: "Vulcan Centaur replaces Atlas V (Russian engines) and Delta IV (expensive). Uses Blue Origin BE-4 engines, 50% cost reduction.", highlight: "50% cost reduction", type: "insight" },
        { title: "National Security", content: "50% of revenue from national security launches—GPS, missile warning, and spy satellites that can't risk failure.", highlight: "Critical NatSec role", type: "insight" },
        { title: "Amazon Kuiper", content: "Largest commercial contract ever: 38 Vulcan launches for Amazon's Kuiper constellation, valued at $2B+.", highlight: "$2B+ Kuiper deal", type: "insight" },
        { title: "Competitive Position", content: "SpaceX is cheaper but ULA has unblemished record for NatSec. Vulcan must prove reliability to maintain share. Captive to parents.", highlight: "Reliability moat", type: "competitive" },
        { title: "Investment Thesis", content: "Private JV—no direct investment. Boeing and Lockheed Martin exposure. Could be acquired or spun out if parents need cash.", highlight: "Parent exposure only", type: "investment" },
      ],
      keyStats: [
        { label: "Consecutive Successes", value: "150+" },
        { label: "Vulcan Launches Sold", value: "70+" },
        { label: "Employees", value: "3,500" },
      ],
      competitors: ["SpaceX", "Blue Origin", "Rocket Lab"],
    },
    // === PROPULSION ===
    {
      id: "ge-aerospace",
      name: "GE Aerospace",
      ticker: "GE",
      logo: "🔧",
      segment: "propulsion",
      description: "World's leading jet engine manufacturer, powering most wide-body aircraft globally.",
      industryRole: "GE Aerospace (with Safran partner CFM) powers 75% of commercial aircraft. No major airline can operate without their engines and services.",
      ceo: "Larry Culp",
      founded: "1917 (aviation)",
      headquarters: "Evendale, Ohio",
      employees: "52,000+",
      marketCap: "$180B+",
      keyProducts: ["LEAP", "GE9X", "CF6", "GE90"],
      recentNews: "Spun off as standalone company in 2024, record engine orders",
      slides: [
        { title: "Engine Duopoly", content: "GE and Pratt & Whitney control virtually all large commercial jet engines. CFM (GE-Safran JV) powers 75% of single-aisle jets.", highlight: "75% of single-aisle", type: "insight" },
        { title: "LEAP Dominance", content: "LEAP engine powers A320neo and 737 MAX—25,000+ engines on order. Most successful engine launch ever.", highlight: "25,000+ LEAP orders", type: "insight" },
        { title: "Services Goldmine", content: "Engine maintenance contracts generate 60% of profits. Airlines are locked in for 20+ years per engine type.", highlight: "60% profit from services", type: "insight" },
        { title: "GE9X Record", content: "GE9X is the world's largest and most powerful commercial jet engine, exclusively powering the Boeing 777X.", highlight: "Largest engine ever", type: "insight" },
        { title: "Competitive Position", content: "Duopoly with Pratt on large engines. GE has 60%+ commercial share. Pratt GTF issues helping GE win more. Rolls-Royce distant third.", highlight: "60%+ share leader", type: "competitive" },
        { title: "Investment Thesis", content: "Best aerospace pure-play post spin-off. Aftermarket razor/blade model is exceptional. Trade travel recovery. Premium deserved.", highlight: "Quality franchise", type: "investment" },
      ],
      keyStats: [
        { label: "Engines in Service", value: "44,000+" },
        { label: "Revenue (2023)", value: "$32B" },
        { label: "Order Backlog", value: "$149B" },
      ],
      competitors: ["Pratt & Whitney", "Rolls-Royce", "Safran"],
    },
    {
      id: "safran",
      name: "Safran",
      ticker: "SAF.PA",
      logo: "🇫🇷",
      segment: "propulsion",
      description: "French aerospace company specializing in engines, landing gear, and aircraft interiors.",
      industryRole: "Safran is GE's partner in CFM International (50/50), making them essential to commercial aviation. Also a leader in landing systems and interiors.",
      ceo: "Olivier Andriès",
      founded: "2005 (merger)",
      headquarters: "Paris, France",
      employees: "83,000+",
      marketCap: "$95B+",
      keyProducts: ["CFM LEAP (with GE)", "Landing Gear", "Aircraft Interiors", "Nacelles"],
      recentNews: "LEAP production ramping to meet Airbus and Boeing demand",
      slides: [
        { title: "CFM Partnership", content: "The CFM 50/50 joint venture with GE is the most successful engine partnership in history. LEAP has 25,000+ orders.", highlight: "50/50 with GE", type: "insight" },
        { title: "Beyond Engines", content: "Safran also leads in landing gear (40% global share), nacelles, and aircraft interiors—diversified aerospace exposure.", highlight: "40% landing gear share", type: "insight" },
        { title: "French Champion", content: "Strategic importance to France means government support for R&D. Leading RISE open-fan engine development for 2035.", highlight: "RISE engine development", type: "insight" },
        { title: "Defense Segment", content: "Guidance systems, drones, and optronics for military applications. M88 engine powers Rafale fighter jets.", highlight: "Rafale engines", type: "insight" },
        { title: "Competitive Position", content: "Tied at hip with GE on CFM. Landing gear duopoly with Collins. Interiors fragmented. Strong across segments.", highlight: "Multi-segment leader", type: "competitive" },
        { title: "Investment Thesis", content: "European aerospace champion. CFM cash flows excellent. EUR-denominated diversification. Trades at premium but quality deserves it.", highlight: "Euro aerospace", type: "investment" },
      ],
      keyStats: [
        { label: "Revenue (2023)", value: "€23.2B" },
        { label: "LEAP Orders", value: "25,000+" },
        { label: "Employees", value: "83,000" },
      ],
      competitors: ["GE Aerospace", "Pratt & Whitney", "Rolls-Royce"],
    },
    {
      id: "rolls-royce",
      name: "Rolls-Royce",
      ticker: "RR.L",
      logo: "🇬🇧",
      segment: "propulsion",
      description: "British aerospace and defense company, second-largest wide-body jet engine maker.",
      industryRole: "Rolls-Royce is the only alternative to GE for wide-body aircraft engines. Also powers nuclear submarines for UK Royal Navy.",
      ceo: "Tufan Erginbilgiç",
      founded: "1906",
      headquarters: "London, UK",
      employees: "42,000+",
      marketCap: "$55B+",
      keyProducts: ["Trent XWB", "Trent 1000", "Pearl Engines", "Nuclear Submarines"],
      recentNews: "Turnaround succeeding, wide-body engine demand recovering strongly",
      slides: [
        { title: "Wide-Body Focus", content: "Trent engines exclusively power Airbus A350 and compete on Boeing 787. Recovery in long-haul flying boosting demand.", highlight: "A350 exclusive", type: "insight" },
        { title: "Business Jets", content: "Pearl engine family powers Gulfstream and Bombardier business jets—the fastest-growing segment.", highlight: "Biz jet growth", type: "insight" },
        { title: "Nuclear Power", content: "Powers all Royal Navy nuclear submarines. Developing small modular reactors (SMRs) for civil power generation.", highlight: "SMR development", type: "insight" },
        { title: "Turnaround Story", content: "New CEO driving cultural transformation. Margins improving, free cash flow returning. Stock up 200%+ from 2022 lows.", highlight: "200%+ stock gain", type: "insight" },
        { title: "Competitive Position", content: "Weak vs GE/Pratt in narrow-body. Captive on A350 but loses 787 share to GE. Biz jets and defense are hedges.", highlight: "Wide-body niche", type: "competitive" },
        { title: "Investment Thesis", content: "Turnaround in progress. Long-haul recovery helps. SMR optionality undervalued. High operating leverage cuts both ways.", highlight: "Turnaround play", type: "investment" },
      ],
      keyStats: [
        { label: "Revenue (2023)", value: "£15.4B" },
        { label: "Engines in Service", value: "13,000+" },
        { label: "Order Book", value: "£79B" },
      ],
      competitors: ["GE Aerospace", "Pratt & Whitney"],
    },
    // === SUPPLIERS ===
    {
      id: "spirit",
      name: "Spirit AeroSystems",
      ticker: "SPR",
      logo: "🏭",
      segment: "suppliers",
      description: "World's largest independent aerostructures manufacturer, building fuselages and components.",
      industryRole: "Spirit builds the fuselages for Boeing 737 and Airbus A350 wing components. A single-source supplier for critical structures.",
      ceo: "Pat Shanahan",
      founded: "2005 (Boeing spin-off)",
      headquarters: "Wichita, Kansas",
      employees: "18,000+",
      marketCap: "$4B+",
      keyProducts: ["737 Fuselages", "A350 Wing Components", "787 Structures", "Defense"],
      recentNews: "Being reacquired by Boeing following quality issues",
      slides: [
        { title: "Fuselage Maker", content: "Spirit builds 70% of every 737 structure—nose, fuselage, engine pylons. No 737 flies without Spirit.", highlight: "70% of 737 structure", type: "insight" },
        { title: "Quality Crisis", content: "2024 door plug incident on 737 MAX traced to Spirit quality issues. Boeing now reacquiring the company.", highlight: "Quality turnaround", type: "insight" },
        { title: "Airbus Work", content: "Also supplies A350 wing components and A220 structures. Diversification beyond Boeing reduces concentration risk.", highlight: "Airbus diversification", type: "insight" },
        { title: "Strategic Importance", content: "Only company that can build 737 fuselages at scale. Critical national security asset for commercial aviation supply chain.", highlight: "Irreplaceable supplier", type: "insight" },
        { title: "Competitive Position", content: "Sole-source on 737 fuselages. Competes with Tier 1 suppliers on other work. Boeing reacquisition removes independence.", highlight: "Boeing captive", type: "competitive" },
        { title: "Investment Thesis", content: "Being acquired by Boeing—limited upside. If deal fails, distressed asset. Quality issues persist. Avoid for new positions.", highlight: "M&A situation", type: "investment" },
      ],
      keyStats: [
        { label: "Revenue (2023)", value: "$6.0B" },
        { label: "Shipsets/Month", value: "40+" },
        { label: "Boeing Revenue %", value: "65%" },
      ],
      competitors: ["Collins Aerospace", "Triumph Group", "GKN Aerospace"],
    },
    {
      id: "howmet",
      name: "Howmet Aerospace",
      ticker: "HWM",
      logo: "⚙️",
      segment: "suppliers",
      description: "Specialty metals and components for jet engines and airframe structures.",
      industryRole: "Howmet makes the critical nickel superalloy components that survive 2000°F inside jet engines. No engine runs without their parts.",
      ceo: "John Plant",
      founded: "2020 (Arconic spin-off)",
      headquarters: "Pittsburgh, Pennsylvania",
      employees: "13,000+",
      marketCap: "$45B+",
      keyProducts: ["Turbine Blades", "Fasteners", "Titanium Structures", "Forged Wheels"],
      recentNews: "Engine aftermarket demand driving record margins",
      slides: [
        { title: "Engine Guts", content: "Howmet's single-crystal turbine blades and superalloy components are in every LEAP and Trent engine. Decades of metallurgy expertise.", highlight: "In every engine", type: "insight" },
        { title: "Fastener Monopoly", content: "80% market share in aerospace fasteners. Billions of fasteners hold aircraft together—specification lock-in prevents switching.", highlight: "80% fastener share", type: "insight" },
        { title: "Margin Expansion", content: "Engine aftermarket growing 15%+ annually as flying hours increase. High-margin spare parts and repairs.", highlight: "15%+ aftermarket growth", type: "insight" },
        { title: "Defense Hedge", content: "30% of revenue from defense applications—F-35, missile systems, helicopter engines. Stable government spending.", highlight: "30% defense", type: "insight" },
        { title: "Competitive Position", content: "Near-monopoly in key engine components. Precision Castparts (Berkshire) is main competitor. Switching costs astronomical.", highlight: "Component monopoly", type: "competitive" },
        { title: "Investment Thesis", content: "Best aerospace supplier. Hidden compounder. Engine aftermarket is perpetual royalty. Valuation stretched but quality premium.", highlight: "Hidden champion", type: "investment" },
      ],
      keyStats: [
        { label: "Revenue (2023)", value: "$6.0B" },
        { label: "EBITDA Margin", value: "24%" },
        { label: "Backlog", value: "$4.7B" },
      ],
      competitors: ["Precision Castparts", "Alcoa", "Carpenter Technology"],
    },
    {
      id: "transdigm",
      name: "TransDigm",
      ticker: "TDG",
      logo: "💰",
      segment: "suppliers",
      description: "Aerospace components conglomerate owning proprietary sole-source parts businesses.",
      industryRole: "TransDigm owns 90+ businesses making niche, proprietary parts that aircraft can't fly without. Their pricing power is legendary (and controversial).",
      ceo: "Kevin Stein",
      founded: "1993",
      headquarters: "Cleveland, Ohio",
      employees: "22,000+",
      marketCap: "$70B+",
      keyProducts: ["Actuators", "Ignition Systems", "Connectors", "Lighting"],
      recentNews: "Continuing acquisition spree, 50% EBITDA margins maintained",
      slides: [
        { title: "Moat Master", content: "TransDigm only buys sole-source, proprietary parts businesses. Once on an aircraft, parts are specified for 30+ years.", highlight: "30+ year lock-in", type: "insight" },
        { title: "Pricing Power", content: "Known for aggressive aftermarket pricing—parts inflation far exceeds general inflation. Pentagon has criticized practices.", highlight: "Pricing controversy", type: "insight" },
        { title: "50% Margins", content: "Highest EBITDA margins in aerospace at 50%+. Private equity DNA focuses relentlessly on profitability.", highlight: "50%+ EBITDA margin", type: "insight" },
        { title: "Acquisition Machine", content: "90+ acquisitions since IPO. Playbook: buy proprietary parts business, raise prices, expand margins, repeat.", highlight: "90+ acquisitions", type: "insight" },
        { title: "Competitive Position", content: "HEICO is only real competitor with different strategy (cheaper PMA parts). Moat from sole-source is unbreakable.", highlight: "Sole-source fortress", type: "competitive" },
        { title: "Investment Thesis", content: "Best business model in aerospace. Controversial but legal. Levered balance sheet is choice. Special dividends. Own for long term.", highlight: "Cash machine", type: "investment" },
      ],
      keyStats: [
        { label: "Revenue (2023)", value: "$6.6B" },
        { label: "EBITDA Margin", value: "50%+" },
        { label: "Acquisitions", value: "90+" },
      ],
      competitors: ["Heico", "Moog", "Woodward"],
    },
    {
      id: "heico",
      name: "HEICO",
      ticker: "HEI",
      logo: "🛠️",
      segment: "suppliers",
      description: "Aerospace and electronics company specializing in aftermarket replacement parts.",
      industryRole: "HEICO is the largest independent maker of FAA-approved aircraft replacement parts, offering 50% savings vs OEM pricing. The anti-TransDigm.",
      ceo: "Laurans Mendelson",
      founded: "1957",
      headquarters: "Hollywood, Florida",
      employees: "9,500+",
      marketCap: "$32B+",
      keyProducts: ["PMA Parts", "Electronic Components", "Flight Support", "Defense Electronics"],
      recentNews: "Continuous market share gains as airlines seek cost savings",
      slides: [
        { title: "PMA Pioneer", content: "HEICO makes Parts Manufacturer Approval (PMA) parts—FAA-certified alternatives to OEM at 30-50% lower cost.", highlight: "30-50% savings", type: "insight" },
        { title: "Airline Favorite", content: "Airlines love HEICO for MRO cost reduction without compromising safety. Growing share in aftermarket.", highlight: "Airlines' choice", type: "insight" },
        { title: "Family Business", content: "Mendelson family has run HEICO for 30+ years. Long-term thinking, conservative balance sheet, employee ownership.", highlight: "Family-controlled", type: "insight" },
        { title: "Electronics Growth", content: "40% of revenue from electronic technologies serving defense, space, and medical markets. Diversification beyond parts.", highlight: "40% electronics", type: "insight" },
        { title: "Competitive Position", content: "Alternative to TransDigm model. Wins on value not pricing power. OEMs hate them. Airlines love them.", highlight: "Value alternative", type: "competitive" },
        { title: "Investment Thesis", content: "Family compounder. 15%+ CAGR for 20+ years. Premium valuation but quality culture. Better risk/reward than TDG for some.", highlight: "Family compounder", type: "investment" },
      ],
      keyStats: [
        { label: "Revenue (2023)", value: "$2.8B" },
        { label: "Acquisitions", value: "95+" },
        { label: "CAGR (20-year)", value: "15%+" },
      ],
      competitors: ["TransDigm", "Collins Aerospace", "Parker Hannifin"],
    },
    {
      id: "moog",
      name: "Moog Inc",
      ticker: "MOG.A",
      logo: "🎛️",
      segment: "suppliers",
      description: "Precision motion control components and systems for aerospace and defense.",
      industryRole: "Moog makes flight control actuators and systems—the muscles that move control surfaces. Critical for both commercial and military aircraft.",
      ceo: "Pat Roche",
      founded: "1951",
      headquarters: "East Aurora, New York",
      employees: "13,000+",
      marketCap: "$5B+",
      keyProducts: ["Flight Controls", "Actuation Systems", "Space Components", "Defense Systems"],
      recentNews: "Winning content on next-gen aircraft programs",
      slides: [
        { title: "Flight Controls", content: "Moog actuators move ailerons, elevators, and rudders on most commercial and military aircraft. 70%+ market share.", highlight: "70%+ actuator share", type: "insight" },
        { title: "Space Heritage", content: "Components on every NASA Mars mission, James Webb, and commercial satellites. 60+ years of space experience.", highlight: "Every Mars mission", type: "insight" },
        { title: "Defense Growth", content: "Missile guidance, naval weapons handling, and military rotorcraft systems. 40% of revenue from defense.", highlight: "40% defense revenue", type: "insight" },
        { title: "Industrial Hedge", content: "Medical devices, energy, and industrial automation provide diversification beyond aerospace cycles.", highlight: "Industrial diversity", type: "insight" },
        { title: "Competitive Position", content: "Leader in actuation with Parker Hannifin second. Switching costs high due to certification requirements.", highlight: "Actuation leader", type: "competitive" },
        { title: "Investment Thesis", content: "Under-followed mid-cap. Next-gen aircraft content growing. Valuation reasonable. Industrial diversification is hedge.", highlight: "Under-followed", type: "investment" },
      ],
      keyStats: [
        { label: "Revenue (2023)", value: "$3.4B" },
        { label: "Aerospace %", value: "60%" },
        { label: "Defense %", value: "40%" },
      ],
      competitors: ["Parker Hannifin", "Collins Aerospace", "Curtiss-Wright"],
    },
    {
      id: "hexcel",
      name: "Hexcel",
      ticker: "HXL",
      logo: "🪨",
      segment: "suppliers",
      description: "Advanced composites manufacturer for aerospace structures.",
      industryRole: "Hexcel makes carbon fiber composites that comprise 50%+ of modern aircraft structures. Boeing 787 and Airbus A350 bodies are primarily Hexcel material.",
      ceo: "Tom Gentile",
      founded: "1948",
      headquarters: "Stamford, Connecticut",
      employees: "6,500+",
      marketCap: "$6B+",
      keyProducts: ["Carbon Fiber", "Prepregs", "Honeycomb", "Composite Structures"],
      recentNews: "Benefiting from wide-body production ramp and composite content growth",
      slides: [
        { title: "Composites Leader", content: "Hexcel supplies carbon fiber and advanced materials for 787, A350, and most military aircraft. 50% content on wide-bodies.", highlight: "50% of wide-body content", type: "insight" },
        { title: "Weight Saver", content: "Composites reduce aircraft weight 20-30% vs aluminum, improving fuel efficiency. Critical for sustainability.", highlight: "20-30% weight savings", type: "insight" },
        { title: "Qualified Supplier", content: "10+ year qualification cycles mean once specified, Hexcel content is locked in for aircraft production life.", highlight: "Locked-in supplier", type: "insight" },
        { title: "Wind Energy", content: "Wind turbine blades use same composite technology. Growing revenue diversification beyond aerospace.", highlight: "Wind turbine blades", type: "insight" },
        { title: "Competitive Position", content: "Duopoly with Toray (Japan) in aerospace composites. High barriers from qualification and IP.", highlight: "Duopoly with Toray", type: "competitive" },
        { title: "Investment Thesis", content: "Wide-body recovery play. Composite content only grows. Cyclical with production rates. Reasonable valuation.", highlight: "Wide-body leverage", type: "investment" },
      ],
      keyStats: [
        { label: "Revenue (2023)", value: "$1.8B" },
        { label: "Aerospace %", value: "70%" },
        { label: "Composite Growth", value: "8% CAGR" },
      ],
      competitors: ["Toray", "Solvay", "Teijin"],
    },
    // === SERVICES ===
    {
      id: "textron",
      name: "Textron Aviation",
      ticker: "TXT",
      logo: "✈️",
      segment: "services",
      description: "Diversified aerospace and defense company owning Cessna, Beechcraft, and Bell Helicopter.",
      industryRole: "Textron dominates general aviation with Cessna and Beechcraft. Bell Helicopter is a leader in military and commercial rotorcraft.",
      ceo: "Scott Donnelly",
      founded: "1923",
      headquarters: "Providence, Rhode Island",
      employees: "35,000+",
      marketCap: "$18B+",
      keyProducts: ["Cessna", "Beechcraft", "Bell Helicopter", "Textron Systems"],
      recentNews: "Bell V-280 Valor selected for U.S. Army Future Long-Range Assault Aircraft",
      slides: [
        { title: "General Aviation King", content: "Cessna Citation is the world's best-selling business jet family. Beechcraft King Air dominates turboprop market.", highlight: "#1 in business jets", type: "insight" },
        { title: "Bell Rotorcraft", content: "Bell V-22 Osprey and new V-280 Valor tiltrotor aircraft. $7B FLRAA contract for 280+ Army helicopters.", highlight: "$7B FLRAA win", type: "insight" },
        { title: "Diverse Portfolio", content: "Also makes unmanned systems, armored vehicles (TAPV), and simulation systems. Defense 25% of revenue.", highlight: "Diversified defense", type: "insight" },
        { title: "Pilot Training", content: "Cessna trainers and piston aircraft remain essential for pilot training worldwide. Gateway to aviation careers.", highlight: "Training aircraft", type: "insight" },
        { title: "Competitive Position", content: "Competes with Gulfstream (larger jets), Bombardier (Challenger), Dassault (Falcon). Bell vs Sikorsky/Airbus Helicopters.", highlight: "Multi-segment player", type: "competitive" },
        { title: "Investment Thesis", content: "Sum-of-parts discount. FLRAA win undervalued. Biz jet cycle turning. Conservative balance sheet. Reasonable entry.", highlight: "Sum-of-parts value", type: "investment" },
      ],
      keyStats: [
        { label: "Revenue (2023)", value: "$13.7B" },
        { label: "Bell Backlog", value: "$6.3B" },
        { label: "Aircraft Delivered", value: "400+" },
      ],
      competitors: ["Gulfstream", "Dassault", "Leonardo"],
    },
    {
      id: "leidos",
      name: "Leidos",
      ticker: "LDOS",
      logo: "💻",
      segment: "services",
      description: "Technology and engineering company focused on defense, intelligence, and civil sectors.",
      industryRole: "Leidos provides IT, engineering, and scientific services to defense and intelligence agencies. Top 10 U.S. defense contractor.",
      ceo: "Tom Bell",
      founded: "1969 (as SAIC)",
      headquarters: "Reston, Virginia",
      employees: "47,000+",
      marketCap: "$18B+",
      keyProducts: ["Defense IT", "Intelligence Services", "Health IT", "Civil Engineering"],
      recentNews: "Winning large-scale IT modernization contracts across government",
      slides: [
        { title: "Government IT", content: "Leidos is a top provider of IT services to DOD, intelligence community, and federal agencies. $15B+ annual revenue.", highlight: "$15B+ revenue", type: "insight" },
        { title: "Defense Engineering", content: "Supports aircraft maintenance, missile defense, and C4ISR systems. Engineering backbone for military operations.", highlight: "Defense engineering", type: "insight" },
        { title: "Health IT", content: "Major contracts with VA and military health systems. Critical for veteran and military healthcare delivery.", highlight: "VA healthcare IT", type: "insight" },
        { title: "Security Clearances", content: "47,000+ employees with security clearances create massive barrier to entry. Trusted by intelligence community.", highlight: "47K+ cleared", type: "insight" },
        { title: "Competitive Position", content: "Competes with SAIC, Booz Allen, GDIT. Cleared workforce is moat. Contract re-competes are risk.", highlight: "Cleared workforce", type: "competitive" },
        { title: "Investment Thesis", content: "Defense services compounder. Less exciting than hardware but steady. AI/cloud modernization tailwind. Reasonable value.", highlight: "Steady services", type: "investment" },
      ],
      keyStats: [
        { label: "Revenue (2023)", value: "$15.4B" },
        { label: "Backlog", value: "$37B" },
        { label: "Cleared Employees", value: "47,000+" },
      ],
      competitors: ["SAIC", "Booz Allen", "General Dynamics IT"],
    },
    {
      id: "leonardo",
      name: "Leonardo",
      ticker: "LDO.MI",
      logo: "🇮🇹",
      segment: "defense",
      description: "Italian aerospace, defense, and security company, Europe's second-largest defense contractor.",
      industryRole: "Leonardo is Italy's national champion for defense and aerospace, with major helicopter, electronics, and aircraft programs.",
      ceo: "Roberto Cingolani",
      founded: "1948",
      headquarters: "Rome, Italy",
      employees: "53,000+",
      marketCap: "$25B+",
      keyProducts: ["AW139 Helicopter", "M-346 Trainer", "Defense Electronics", "Cyber Security"],
      recentNews: "Increasing European defense spending driving order growth",
      slides: [
        { title: "Helicopter Leader", content: "AgustaWestland helicopters (AW139, AW101) are best-sellers globally. 50%+ of revenue from helicopters.", highlight: "50%+ helicopter revenue", type: "insight" },
        { title: "Trainer Aircraft", content: "M-346 is the world's most advanced jet trainer, selected by Italy, Poland, Israel, and others.", highlight: "M-346 trainer leader", type: "insight" },
        { title: "Defense Electronics", content: "Radars, sensors, and electronic warfare systems for European and NATO programs.", highlight: "NATO electronics", type: "insight" },
        { title: "European Consolidation", content: "Potential combination with other European defense firms as continent ramps spending post-Ukraine.", highlight: "Consolidation target", type: "insight" },
        { title: "Competitive Position", content: "Competes with Airbus Helicopters, BAE, Thales. Smaller scale than U.S. primes. European focus.", highlight: "European niche", type: "competitive" },
        { title: "Investment Thesis", content: "Cheapest European defense name. Italy discount may be unwarranted. Helicopter franchise undervalued. EUR exposure.", highlight: "Value European", type: "investment" },
      ],
      keyStats: [
        { label: "Revenue (2023)", value: "€15.3B" },
        { label: "Backlog", value: "€39B" },
        { label: "Helicopters Delivered", value: "4,500+" },
      ],
      competitors: ["Airbus Helicopters", "BAE Systems", "Thales"],
    },
    {
      id: "saic",
      name: "SAIC",
      ticker: "SAIC",
      logo: "🏛️",
      segment: "services",
      description: "Technology integrator focused on defense, space, civilian, and intelligence markets.",
      industryRole: "SAIC provides systems integration, IT services, and engineering to U.S. government. Essential for modernizing government technology.",
      ceo: "Toni Townes-Whitley",
      founded: "2013 (split from Leidos)",
      headquarters: "Reston, Virginia",
      employees: "24,000+",
      marketCap: "$6B+",
      keyProducts: ["IT Services", "Systems Integration", "Engineering", "Training"],
      recentNews: "Focus on AI, cloud, and digital transformation for government",
      slides: [
        { title: "Government Focus", content: "95% of revenue from U.S. government contracts. Deep relationships across DOD, intelligence, and civilian agencies.", highlight: "95% government", type: "insight" },
        { title: "NASA Heritage", content: "Long history supporting NASA missions. Key contractor for space exploration and science programs.", highlight: "NASA partner", type: "insight" },
        { title: "IT Modernization", content: "Helping agencies migrate to cloud, implement AI, and modernize legacy systems. Growing addressable market.", highlight: "Cloud migration", type: "insight" },
        { title: "Smaller Scale", content: "Positioned between mega-primes and small contractors. Agile enough to innovate, large enough to scale.", highlight: "Right-sized integrator", type: "insight" },
        { title: "Competitive Position", content: "Competes with Leidos, Booz Allen, GDIT. Smaller scale limits prime contractor wins. Subcontracting common.", highlight: "Mid-tier integrator", type: "competitive" },
        { title: "Investment Thesis", content: "Cheapest defense services name. New CEO driving change. IT modernization tailwind. Value but show-me story.", highlight: "Value services", type: "investment" },
      ],
      keyStats: [
        { label: "Revenue (2023)", value: "$7.4B" },
        { label: "Backlog", value: "$23B" },
        { label: "Government %", value: "95%" },
      ],
      competitors: ["Leidos", "Booz Allen", "General Dynamics IT"],
    },
    {
      id: "curtiss-wright",
      name: "Curtiss-Wright",
      ticker: "CW",
      logo: "🦅",
      segment: "suppliers",
      description: "Diversified industrial company providing engineered products for aerospace, defense, and power.",
      industryRole: "Curtiss-Wright makes critical components for aircraft, ships, and nuclear power plants. A hidden infrastructure essential.",
      ceo: "Lynn Bamford",
      founded: "1929 (merger)",
      headquarters: "Davidson, North Carolina",
      employees: "8,000+",
      marketCap: "$12B+",
      keyProducts: ["Flight Actuators", "Naval Components", "Nuclear Instruments", "Sensors"],
      recentNews: "Defense and nuclear power markets driving growth",
      slides: [
        { title: "Historic Name", content: "Formed from merger of Wright brothers' and Glenn Curtiss' companies—aviation pioneer heritage.", highlight: "Wright brothers legacy", type: "insight" },
        { title: "Naval Systems", content: "Critical components on every U.S. Navy ship and submarine. Virginia-class subs drive recurring revenue.", highlight: "On every Navy ship", type: "insight" },
        { title: "Nuclear Power", content: "Reactor coolant pumps and instrumentation for commercial and Navy nuclear programs.", highlight: "Nuclear expertise", type: "insight" },
        { title: "Defense Tailwinds", content: "Bookings growing 20%+ as defense budgets increase. Positioned across all major platforms.", highlight: "20%+ booking growth", type: "insight" },
        { title: "Competitive Position", content: "Competes with Moog, Parker, Woodward in actuation. Nuclear is specialized niche with few competitors.", highlight: "Multi-niche player", type: "competitive" },
        { title: "Investment Thesis", content: "Quality small-cap. Defense + nuclear + aerospace combo unique. Under-followed by Wall Street. Compounding quietly.", highlight: "Quality small-cap", type: "investment" },
      ],
      keyStats: [
        { label: "Revenue (2023)", value: "$2.9B" },
        { label: "Defense %", value: "50%" },
        { label: "Operating Margin", value: "17%" },
      ],
      competitors: ["Moog", "Parker Hannifin", "Woodward"],
    },
    {
      id: "kratos",
      name: "Kratos Defense",
      ticker: "KTOS",
      logo: "🎯",
      segment: "defense",
      description: "Defense technology company specializing in unmanned systems and hypersonic vehicles.",
      industryRole: "Kratos is leading the affordable attritable drone revolution. Their XQ-58 Valkyrie concept could transform air combat economics.",
      ceo: "Eric DeMarco",
      founded: "1994",
      headquarters: "San Diego, California",
      employees: "4,000+",
      marketCap: "$4B+",
      keyProducts: ["XQ-58 Valkyrie", "Target Drones", "Satellite Systems", "Hypersonic Components"],
      recentNews: "Autonomous collaborative combat aircraft gaining Pentagon attention",
      slides: [
        { title: "Drone Pioneer", content: "Kratos pioneered affordable jet-powered drones. XQ-58 Valkyrie concept proved attritable autonomy is possible.", highlight: "Valkyrie pioneer", type: "insight" },
        { title: "Attritable Vision", content: "$2-3M drones vs $100M fighters changes combat math. Swarms of low-cost platforms may dominate future warfare.", highlight: "$2-3M per drone", type: "insight" },
        { title: "Target Drones", content: "World's largest provider of aerial target drones for military training. Stable, recurring revenue base.", highlight: "#1 target drones", type: "insight" },
        { title: "Hypersonic Tech", content: "Making components and subsystems for classified hypersonic programs. High-growth defense priority.", highlight: "Hypersonic exposure", type: "insight" },
        { title: "Competitive Position", content: "Competes with General Atomics (large drones), Anduril (autonomous). First-mover in attritable segment.", highlight: "First-mover attritable", type: "competitive" },
        { title: "Investment Thesis", content: "High-growth defense disruptor. Unprofitable but revenue growing 20%+. Binary outcomes on big programs. Speculative.", highlight: "Speculative growth", type: "investment" },
      ],
      keyStats: [
        { label: "Revenue (2023)", value: "$1.0B" },
        { label: "Drones Delivered", value: "1,000+" },
        { label: "Backlog", value: "$1.2B" },
      ],
      competitors: ["General Atomics", "Northrop Grumman", "Anduril"],
    },
    {
      id: "anduril",
      name: "Anduril Industries",
      logo: "⚔️",
      segment: "defense",
      description: "Defense technology company building autonomous systems and AI-powered military capabilities.",
      industryRole: "Anduril represents the new wave of defense tech, bringing Silicon Valley speed and AI-first thinking to national security.",
      ceo: "Palmer Luckey",
      founded: "2017",
      headquarters: "Costa Mesa, California",
      employees: "2,500+",
      marketCap: "$14B+ (private)",
      keyProducts: ["Lattice OS", "Ghost Drones", "Sentry Towers", "Dive Submarines"],
      recentNews: "Explosive growth, $8B+ in DoD contracts, major ICBM pursuits",
      slides: [
        { title: "Defense Disruptor", content: "Founded by Oculus VR's Palmer Luckey, Anduril is challenging traditional primes with software-first approach.", highlight: "Software-first defense", type: "insight" },
        { title: "Lattice Platform", content: "Their AI operating system, Lattice, fuses sensors and enables autonomous decision-making across all products.", highlight: "AI backbone", type: "insight" },
        { title: "Hypergrowth", content: "Revenue reportedly 3x in 2023. Won $1B+ contract to build anti-drone systems at scale.", highlight: "3x revenue growth", type: "insight" },
        { title: "Prime Ambitions", content: "Now competing for major programs like Sentinel ICBM. Wants to become a new generation defense prime.", highlight: "Next-gen prime", type: "insight" },
        { title: "Competitive Position", content: "Competes with Palantir (software), traditional primes (hardware). Unique combo of both. Execution is proving out.", highlight: "Unique position", type: "competitive" },
        { title: "Investment Thesis", content: "Private at $14B valuation. Could IPO within 2-3 years. Transformational if execution continues. High risk, high reward.", highlight: "Private, exciting", type: "investment" },
      ],
      keyStats: [
        { label: "Valuation", value: "$14B+" },
        { label: "DoD Contracts", value: "$8B+" },
        { label: "Employees", value: "2,500+" },
      ],
      competitors: ["Palantir", "Northrop Grumman", "Shield AI"],
    },
    {
      id: "aerojet",
      name: "Aerojet Rocketdyne",
      logo: "🚀",
      segment: "propulsion",
      description: "Rocket and missile propulsion company, sole U.S. maker of many critical rocket motors.",
      industryRole: "Aerojet Rocketdyne makes the rocket engines that power virtually all U.S. missiles and launch vehicles. A strategic national asset.",
      ceo: "Part of L3Harris",
      founded: "1942",
      headquarters: "El Segundo, California",
      employees: "5,000+",
      marketCap: "Acquired by L3Harris",
      keyProducts: ["RS-25 (SLS)", "RL-10", "Missile Motors", "Hypersonic Propulsion"],
      recentNews: "Acquired by L3Harris for $4.7B in 2023",
      slides: [
        { title: "Sole Source", content: "Only U.S. producer for many critical rocket motors including RS-25 (Space Launch System) and various missile propulsion.", highlight: "Only U.S. producer", type: "insight" },
        { title: "Heritage Engines", content: "RS-25 powered every Space Shuttle mission and now SLS. RL-10 upper stage engine has 500+ mission heritage.", highlight: "500+ mission heritage", type: "insight" },
        { title: "Missile Backbone", content: "Solid and liquid propulsion for Patriot, THAAD, SM-3, and most U.S. missile systems.", highlight: "Powers U.S. missiles", type: "insight" },
        { title: "L3Harris Synergy", content: "Now part of L3Harris, creating vertical integration from propulsion to complete weapon systems.", highlight: "L3Harris integration", type: "insight" },
        { title: "Competitive Position", content: "Northrop competes in solid motors. SpaceX/Blue Origin in launch. But Aerojet has heritage and sole-source positions.", highlight: "Heritage sole-source", type: "competitive" },
        { title: "Investment Thesis", content: "Acquired—invest via L3Harris (LHX). Propulsion capability strengthens L3Harris competitive position.", highlight: "L3Harris exposure", type: "investment" },
      ],
      keyStats: [
        { label: "Acquisition Price", value: "$4.7B" },
        { label: "Revenue (2022)", value: "$2.3B" },
        { label: "Major Programs", value: "100+" },
      ],
      competitors: ["Northrop Grumman (propulsion)", "Ursa Major", "SpaceX (Merlin/Raptor)"],
    },
    {
      id: "sierra-space",
      name: "Sierra Space",
      logo: "🌌",
      segment: "space",
      description: "Commercial space company developing Dream Chaser spaceplane and orbital habitats.",
      industryRole: "Sierra Space is building the commercial infrastructure for the post-ISS era, including cargo delivery and private space stations.",
      ceo: "Tom Vice",
      founded: "2021 (spin-off)",
      headquarters: "Louisville, Colorado",
      employees: "1,500+",
      marketCap: "$5B+ (private)",
      keyProducts: ["Dream Chaser", "LIFE Habitat", "In-Space Manufacturing"],
      recentNews: "Dream Chaser first mission to ISS expected 2024",
      slides: [
        { title: "Spaceplane Return", content: "Dream Chaser is the only winged, runway-landing spacecraft since Space Shuttle. Enables gentle cargo return.", highlight: "Runway landing", type: "insight" },
        { title: "NASA Cargo", content: "NASA Commercial Resupply contract worth $2B+ for 7 cargo missions to ISS through 2028.", highlight: "$2B+ NASA contract", type: "insight" },
        { title: "Orbital Habitats", content: "LIFE inflatable habitats designed for commercial space stations as ISS retires in 2030.", highlight: "Post-ISS leader", type: "insight" },
        { title: "In-Space Economy", content: "Vision for manufacturing, tourism, and research in orbit. Partnered with Blue Origin's Orbital Reef.", highlight: "Orbital Reef partner", type: "insight" },
        { title: "Competitive Position", content: "SpaceX Dragon dominates cargo. Dream Chaser differentiated by runway landing. Habitats vs Axiom.", highlight: "Differentiated capability", type: "competitive" },
        { title: "Investment Thesis", content: "Private. IPO possible within 2-3 years. Early-stage space infrastructure. High risk but post-ISS opportunity is real.", highlight: "Post-ISS bet", type: "investment" },
      ],
      keyStats: [
        { label: "NASA Missions", value: "7 contracted" },
        { label: "Valuation", value: "$5B+" },
        { label: "Dream Chaser Flights", value: "0 (2024 debut)" },
      ],
      competitors: ["SpaceX (Dragon)", "Axiom Space", "Nanoracks"],
    },
    {
      id: "axiom",
      name: "Axiom Space",
      logo: "🛸",
      segment: "space",
      description: "Commercial space station company building the first private orbital habitat.",
      industryRole: "Axiom is leading the transition from government-owned ISS to commercial space stations, with NASA's blessing and funding.",
      ceo: "Michael Suffredini",
      founded: "2016",
      headquarters: "Houston, Texas",
      employees: "800+",
      marketCap: "$2B+ (private)",
      keyProducts: ["Axiom Station Modules", "Private Astronaut Missions", "Space Suits"],
      recentNews: "Axiom Station modules attaching to ISS, then separating as standalone station",
      slides: [
        { title: "ISS Successor", content: "NASA selected Axiom to build first commercial station modules, initially attached to ISS, then separating in 2028+.", highlight: "ISS successor", type: "insight" },
        { title: "Private Astronauts", content: "Operating private astronaut missions to ISS—Ax-1, Ax-2, Ax-3. Gateway to space for private citizens and nations.", highlight: "Private missions", type: "insight" },
        { title: "AxEMU Suits", content: "Developing next-generation spacesuits for NASA Artemis moonwalks. $228M contract for lunar exploration suits.", highlight: "Artemis spacesuits", type: "insight" },
        { title: "Sovereign Access", content: "Offering countries without space programs their own national astronaut access and research capabilities.", highlight: "National access", type: "insight" },
        { title: "Competitive Position", content: "Lead in commercial stations. Sierra Space is partner not competitor. Blue Origin Orbital Reef is main rival.", highlight: "Station leader", type: "competitive" },
        { title: "Investment Thesis", content: "Private at $2B+. Essential post-ISS infrastructure. NASA backing reduces risk. Early but transformational opportunity.", highlight: "Essential infrastructure", type: "investment" },
      ],
      keyStats: [
        { label: "Missions Completed", value: "3" },
        { label: "Valuation", value: "$2B+" },
        { label: "NASA Contracts", value: "$500M+" },
      ],
      competitors: ["Sierra Space", "Blue Origin", "Vast"],
    },
  ],
};

export const defaultCompanies: Company[] = [
  {
    id: "coming-soon",
    name: "Coming Soon",
    logo: "📊",
    segment: "commercial",
    description: "Key players for this market will be added soon.",
    industryRole: "To be determined",
    ceo: "TBD",
    founded: "TBD",
    headquarters: "TBD",
    employees: "TBD",
    keyProducts: [],
    slides: [],
  },
];