export interface CompanySlide {
  title: string;
  content: string;
  highlight?: string;
  type?: "insight" | "competitive" | "investment";
}

export interface Company {
  id: string;
  name: string;
  ticker?: string;
  logo: string;
  logoUrl?: string; // Real company logo URL
  description: string;
  ceo: string;
  founded: string;
  headquarters: string;
  employees: string;
  marketCap?: string;
  keyProducts: string[];
  recentNews?: string;
  segment: "commercial" | "defense" | "space" | "propulsion" | "suppliers" | "services" | "devices" | "therapeutics" | "pharma";
  industryRole: string;
  slides: CompanySlide[];
  keyStats?: {
    label: string;
    value: string;
  }[];
  competitors?: string[];
}

export interface MarketCompanies {
  [marketId: string]: Company[];
}

// Company logo URLs (using reliable sources with fallbacks)
// Using img.logo.dev which is more reliable than clearbit
const getLogoUrl = (domain: string) => `https://img.logo.dev/${domain}?token=pk_X-1ZO13GSgeOoUrIuJ6GMQ`;

const LOGOS = {
  // Aerospace
  boeing: getLogoUrl("boeing.com"),
  airbus: getLogoUrl("airbus.com"),
  embraer: getLogoUrl("embraer.com"),
  lockheed: getLogoUrl("lockheedmartin.com"),
  northrop: getLogoUrl("northropgrumman.com"),
  raytheon: getLogoUrl("rtx.com"),
  gd: getLogoUrl("gd.com"),
  l3harris: getLogoUrl("l3harris.com"),
  spacex: getLogoUrl("spacex.com"),
  blueorigin: getLogoUrl("blueorigin.com"),
  rocketlab: getLogoUrl("rocketlabusa.com"),
  relativity: getLogoUrl("relativityspace.com"),
  ge: getLogoUrl("geaerospace.com"),
  safran: getLogoUrl("safran-group.com"),
  rollsroyce: getLogoUrl("rolls-royce.com"),
  honeywell: getLogoUrl("honeywell.com"),
  transdigm: getLogoUrl("transdigm.com"),
  hexcel: getLogoUrl("hexcel.com"),
  spirit: getLogoUrl("spiritaero.com"),
  textron: getLogoUrl("textron.com"),
  heico: getLogoUrl("heico.com"),
  joby: getLogoUrl("jobyaviation.com"),
  archer: getLogoUrl("archer.com"),
  lilium: getLogoUrl("lilium.com"),
  beta: getLogoUrl("beta.team"),
  boom: getLogoUrl("boomsupersonic.com"),
  hermeus: getLogoUrl("hermeus.com"),
  axiom: getLogoUrl("axiomspace.com"),
  anduril: getLogoUrl("anduril.com"),
  shield: getLogoUrl("shieldai.com"),
  aerojet: getLogoUrl("rocket.com"),
  // Neuroscience
  neuralink: getLogoUrl("neuralink.com"),
  synchron: getLogoUrl("synchron.com"),
  blackrock: getLogoUrl("blackrockneurotech.com"),
  kernel: getLogoUrl("kernel.com"),
  openwater: getLogoUrl("openwater.health"),
  muse: getLogoUrl("choosemuse.com"),
  emotiv: getLogoUrl("emotiv.com"),
  nextmind: getLogoUrl("next-mind.com"),
  pear: getLogoUrl("peartherapeutics.com"),
  compass: getLogoUrl("compasspathways.com"),
  atai: getLogoUrl("atai.life"),
  biogen: getLogoUrl("biogen.com"),
  abbvie: getLogoUrl("abbvie.com"),
  lilly: getLogoUrl("lilly.com"),
  medtronic: getLogoUrl("medtronic.com"),
  abbott: getLogoUrl("abbott.com"),
};

export const marketCompanies: MarketCompanies = {
  aerospace: [
    // === COMMERCIAL AVIATION ===
    {
      id: "boeing",
      name: "Boeing",
      ticker: "BA",
      logo: "✈️",
      logoUrl: LOGOS.boeing,
      segment: "commercial",
      description: "The world's largest aerospace company and leading manufacturer of commercial jetliners, defense, space and security systems.",
      industryRole: "Boeing is one of two major commercial aircraft manufacturers globally (duopoly with Airbus). They define industry standards for wide-body aircraft and have massive influence on supply chains.",
      ceo: "Kelly Ortberg",
      founded: "1916",
      headquarters: "Arlington, Virginia",
      employees: "170,000+",
      marketCap: "$120B+",
      keyProducts: ["737 MAX", "787 Dreamliner", "777X", "Defense & Space"],
      recentNews: "Focus on safety improvements and production ramp-up of 737 MAX",
      slides: [
        { title: "Industry Giant", content: "Boeing commands ~40% of the global commercial aircraft market, delivering 500+ aircraft annually. Their backlog exceeds $500B.", highlight: "$500B+ backlog", type: "insight" },
        { title: "Vertical Integration", content: "Unlike Airbus, Boeing owns more of its supply chain, from fuselages to avionics. This gives them control but also concentration risk.", highlight: "Vertically integrated", type: "insight" },
        { title: "Defense Pillar", content: "Boeing's defense segment generates ~40% of revenue, providing stability during commercial downturns. Key programs include F-15EX and KC-46 tanker.", highlight: "40% defense revenue", type: "insight" },
        { title: "Space Ambitions", content: "Through Starliner and Space Launch System (SLS), Boeing is NASA's primary commercial crew partner alongside SpaceX.", highlight: "NASA partner", type: "insight" },
        { title: "Competitive Position", content: "Boeing trails Airbus in orders but dominates wide-body with 787/777. Quality issues have eroded trust. Main threats: Airbus execution, COMAC long-term.", highlight: "Wide-body leader", type: "competitive" },
        { title: "Investment Thesis", content: "Turnaround play with new CEO. Massive backlog provides visibility. Key risks: quality execution, MAX reputation, defense cost overruns. Buy on stabilization.", highlight: "Turnaround story", type: "investment" },
      ],
      keyStats: [
        { label: "Aircraft Delivered (2024)", value: "528" },
        { label: "Order Backlog", value: "5,600+" },
        { label: "Revenue", value: "$77.8B" },
      ],
      competitors: ["Airbus", "Embraer", "COMAC"],
    },
    {
      id: "airbus",
      name: "Airbus",
      ticker: "AIR.PA",
      logo: "🌐",
      logoUrl: LOGOS.airbus,
      segment: "commercial",
      description: "European multinational aerospace corporation and one of the world's largest aircraft manufacturers.",
      industryRole: "Airbus is Boeing's only true competitor in large commercial aircraft. They've captured market share through the fuel-efficient A320neo family and have a stronger order book.",
      ceo: "Guillaume Faury",
      founded: "1970",
      headquarters: "Leiden, Netherlands",
      employees: "130,000+",
      marketCap: "$150B+",
      keyProducts: ["A320neo", "A350", "A380", "Helicopters"],
      recentNews: "Record deliveries and strong order backlog exceeding 8,000 aircraft",
      slides: [
        { title: "Market Leader", content: "Airbus delivered 735 aircraft in 2023, outselling Boeing. Their A320neo family dominates the single-aisle segment with 60%+ market share.", highlight: "735 deliveries in 2023", type: "insight" },
        { title: "European Champion", content: "Backed by France, Germany, Spain, and UK governments, Airbus represents European aerospace sovereignty and employs 130,000+ across the continent.", highlight: "Pan-European", type: "insight" },
        { title: "Innovation Focus", content: "Leading the ZEROe hydrogen aircraft initiative, targeting zero-emission commercial flight by 2035. Also investing heavily in sustainable aviation fuels.", highlight: "Hydrogen by 2035", type: "insight" },
        { title: "Helicopter Dominance", content: "Airbus Helicopters is the world's largest civil and parapublic helicopter manufacturer with 50%+ market share.", highlight: "#1 in helicopters", type: "insight" },
        { title: "Competitive Position", content: "Winning the single-aisle war with A320neo. Boeing's troubles gift market share. Risks: supply chain constraints, engine availability limiting production ramp.", highlight: "Single-aisle winner", type: "competitive" },
        { title: "Investment Thesis", content: "Premium aerospace franchise with pricing power. Decade of deliveries locked in. Trade at premium to Boeing for good reason. Best pure-play on aviation recovery.", highlight: "Quality compounder", type: "investment" },
      ],
      keyStats: [
        { label: "Aircraft Delivered (2023)", value: "735" },
        { label: "Order Backlog", value: "8,600+" },
        { label: "Revenue", value: "€65.4B" },
      ],
      competitors: ["Boeing", "COMAC", "Embraer"],
    },
    {
      id: "embraer",
      name: "Embraer",
      ticker: "ERJ",
      logo: "🇧🇷",
      logoUrl: LOGOS.embraer,
      segment: "commercial",
      description: "Brazilian aerospace company specializing in regional jets and executive aviation.",
      industryRole: "Embraer dominates the regional jet market (70-150 seats) where Boeing and Airbus don't compete directly. They're the third-largest aircraft manufacturer globally.",
      ceo: "Francisco Gomes Neto",
      founded: "1969",
      headquarters: "São José dos Campos, Brazil",
      employees: "19,000+",
      marketCap: "$7B+",
      keyProducts: ["E-Jet E2", "Phenom", "Praetor", "KC-390"],
      recentNews: "E2 family gaining orders as airlines seek right-sized aircraft",
      slides: [
        { title: "Regional King", content: "Embraer controls ~60% of the regional jet market with its E-Jet family. Airlines choose them when 737/A320 capacity is too large.", highlight: "60% regional market", type: "insight" },
        { title: "Executive Jets", content: "Their Phenom and Praetor lines compete with Bombardier and Gulfstream in the lucrative business jet segment.", highlight: "Business aviation", type: "insight" },
        { title: "Defense Export", content: "The KC-390 military transport is gaining traction as a C-130 alternative, with orders from Portugal, Hungary, and Netherlands.", highlight: "KC-390 exports", type: "insight" },
        { title: "Failed Boeing Deal", content: "A 2020 merger with Boeing's commercial division collapsed, leaving Embraer independent but stronger, now exploring partnerships.", highlight: "Independent survivor", type: "insight" },
        { title: "Competitive Position", content: "Owns the regional niche Boeing/Airbus abandoned. Bombardier exit strengthens position. Threat: airlines up-gauging to A220/MAX.", highlight: "Niche dominance", type: "competitive" },
        { title: "Investment Thesis", content: "Undervalued relative to peers. E2 cycle ramping. Defense exports diversify. Potential M&A target. Brazilian currency adds volatility.", highlight: "Undervalued niche", type: "investment" },
      ],
      keyStats: [
        { label: "Aircraft Delivered (2023)", value: "181" },
        { label: "Backlog Value", value: "$21B" },
        { label: "Revenue", value: "$5.3B" },
      ],
      competitors: ["Bombardier", "ATR", "Mitsubishi"],
    },
    // === DEFENSE ===
    {
      id: "lockheed",
      name: "Lockheed Martin",
      ticker: "LMT",
      logo: "🛡️",
      logoUrl: LOGOS.lockheed,
      segment: "defense",
      description: "Global security and aerospace company focused on defense, space, and advanced technology systems.",
      industryRole: "The world's largest defense contractor. Lockheed sets the standard for 5th-generation fighters and is the prime contractor for critical national security programs.",
      ceo: "Jim Taiclet",
      founded: "1995 (merger)",
      headquarters: "Bethesda, Maryland",
      employees: "116,000+",
      marketCap: "$140B+",
      keyProducts: ["F-35 Lightning II", "C-130 Hercules", "Missiles & Fire Control", "Sikorsky Helicopters"],
      recentNews: "F-35 production ramping to 156 jets/year, massive international demand",
      slides: [
        { title: "Defense Titan", content: "Lockheed receives more U.S. defense dollars than any other company—$75B+ annually. The F-35 alone is a $1.7 trillion lifetime program.", highlight: "$1.7T F-35 program", type: "insight" },
        { title: "F-35 Dominance", content: "The F-35 is the backbone of Western air power, with 900+ delivered to 18 nations. It's the most expensive weapon system in history.", highlight: "900+ F-35s delivered", type: "insight" },
        { title: "Space Systems", content: "Lockheed builds GPS satellites, missile warning systems, and the Orion spacecraft for NASA's Artemis moon missions.", highlight: "Artemis partner", type: "insight" },
        { title: "Hypersonic Race", content: "Leading U.S. hypersonic weapons development with programs like ARRW and Dark Eagle, competing with China and Russia.", highlight: "Hypersonic leader", type: "insight" },
        { title: "Competitive Position", content: "Unassailable in 5th-gen fighters. F-35 lock-in creates 50+ year revenue stream. Northrop and RTX compete in missiles/space but not aircraft.", highlight: "Fighter monopoly", type: "competitive" },
        { title: "Investment Thesis", content: "Defense budget tailwinds for decade. F-35 annuity business. 3% dividend yield. Low beta hedge. Limited upside but sleep-well-at-night defense.", highlight: "Defense bond", type: "investment" },
      ],
      keyStats: [
        { label: "Revenue (2023)", value: "$67.6B" },
        { label: "Backlog", value: "$160B+" },
        { label: "F-35 Delivered", value: "950+" },
      ],
      competitors: ["Northrop Grumman", "Raytheon", "Boeing Defense"],
    },
    {
      id: "northrop",
      name: "Northrop Grumman",
      ticker: "NOC",
      logo: "🦅",
      logoUrl: LOGOS.northrop,
      segment: "defense",
      description: "Global aerospace and defense technology company known for stealth aircraft and space systems.",
      industryRole: "Northrop is the stealth technology leader, building America's most advanced bombers and unmanned systems. They're essential to nuclear deterrence.",
      ceo: "Kathy Warden",
      founded: "1994 (merger)",
      headquarters: "Falls Church, Virginia",
      employees: "95,000+",
      marketCap: "$80B+",
      keyProducts: ["B-21 Raider", "James Webb Telescope", "Global Hawk", "Sentinel ICBM"],
      recentNews: "B-21 Raider stealth bomber unveiled, production ramping up",
      slides: [
        { title: "Stealth Pioneer", content: "Northrop built the B-2 Spirit and now the B-21 Raider—the world's most advanced stealth bombers. Only they have this capability.", highlight: "Only B-21 maker", type: "insight" },
        { title: "Nuclear Triad", content: "Building the Sentinel ICBM to replace Minuteman III, a $100B+ program ensuring U.S. nuclear deterrence for decades.", highlight: "$100B Sentinel", type: "insight" },
        { title: "Space Excellence", content: "Built the James Webb Space Telescope and key components for national security satellites. Space revenue is ~25% of total.", highlight: "James Webb builder", type: "insight" },
        { title: "Autonomous Systems", content: "Global Hawk drones have flown 500,000+ hours. MQ-4C Triton expands Navy surveillance capabilities globally.", highlight: "500K+ drone hours", type: "insight" },
        { title: "Competitive Position", content: "Sole-source on B-21 and Sentinel—crown jewels. Competes with Lockheed on space, RTX on missiles. Moat in stealth unmatched.", highlight: "Stealth monopoly", type: "competitive" },
        { title: "Investment Thesis", content: "Highest-quality defense franchise. B-21 and Sentinel provide 30+ year visibility. Premium valuation deserved. Add on pullbacks.", highlight: "Premium defense", type: "investment" },
      ],
      keyStats: [
        { label: "Revenue (2023)", value: "$39.3B" },
        { label: "Backlog", value: "$84B+" },
        { label: "Employees", value: "95,000" },
      ],
      competitors: ["Lockheed Martin", "Boeing", "General Atomics"],
    },
    {
      id: "raytheon",
      name: "RTX (Raytheon)",
      ticker: "RTX",
      logo: "🎯",
      logoUrl: LOGOS.raytheon,
      segment: "defense",
      description: "Aerospace and defense conglomerate formed from Raytheon and United Technologies merger.",
      industryRole: "RTX is the missiles and sensors powerhouse. When a military needs precision-guided weapons or advanced radar, Raytheon is often the only option.",
      ceo: "Chris Calio",
      founded: "2020 (merger)",
      headquarters: "Arlington, Virginia",
      employees: "180,000+",
      marketCap: "$150B+",
      keyProducts: ["Patriot Missiles", "Stinger", "Pratt & Whitney Engines", "Collins Aerospace"],
      recentNews: "Massive demand for Patriot systems and Stinger missiles due to Ukraine conflict",
      slides: [
        { title: "Merged Giant", content: "2020 merger of Raytheon (missiles) and United Technologies (Pratt engines, Collins avionics) created a $70B+ revenue powerhouse.", highlight: "$70B+ revenue", type: "insight" },
        { title: "Missile Monopoly", content: "Raytheon makes Patriot, Stinger, Tomahawk, and AMRAAM missiles. Ukraine conflict depleted inventories, creating years of backlog.", highlight: "Ukraine surge", type: "insight" },
        { title: "Engine Empire", content: "Pratt & Whitney powers 25% of commercial aircraft (A320neo, 787) and 100% of F-35s. A critical strategic asset.", highlight: "25% of aircraft", type: "insight" },
        { title: "Avionics Leader", content: "Collins Aerospace supplies cockpits, sensors, and systems to virtually every major aircraft program globally.", highlight: "Universal supplier", type: "insight" },
        { title: "Competitive Position", content: "Only Lockheed competes broadly. Pratt duopoly with GE. Collins near-monopoly on avionics. GTF engine issues temporary headwind.", highlight: "Diversified leader", type: "competitive" },
        { title: "Investment Thesis", content: "Best balance of defense + commercial. Ukraine restocking drives missiles. Pratt issues priced in. Dividend aristocrat. Core holding.", highlight: "Balanced exposure", type: "investment" },
      ],
      keyStats: [
        { label: "Revenue (2023)", value: "$68.9B" },
        { label: "Backlog", value: "$196B" },
        { label: "Employees", value: "180,000" },
      ],
      competitors: ["Lockheed Martin", "Northrop Grumman", "L3Harris"],
    },
    {
      id: "gd",
      name: "General Dynamics",
      ticker: "GD",
      logo: "⚓",
      logoUrl: LOGOS.gd,
      segment: "defense",
      description: "Diversified defense company spanning submarines, land systems, IT, and business jets.",
      industryRole: "General Dynamics builds America's nuclear submarines and main battle tanks—the backbone of naval and ground deterrence. Also owns Gulfstream.",
      ceo: "Phebe Novakovic",
      founded: "1952",
      headquarters: "Reston, Virginia",
      employees: "106,000+",
      marketCap: "$75B+",
      keyProducts: ["Virginia-class Submarines", "Abrams Tank", "Gulfstream Jets", "IT Services"],
      recentNews: "Columbia-class submarine program critical to nuclear deterrence",
      slides: [
        { title: "Submarine Maker", content: "Electric Boat division is one of only two U.S. submarine builders. Columbia-class boomers are a $130B program for nuclear deterrence.", highlight: "$130B submarine program", type: "insight" },
        { title: "Ground Combat", content: "The M1 Abrams tank remains the West's premier main battle tank. Stryker vehicles provide Army mobility globally.", highlight: "Abrams dominance", type: "insight" },
        { title: "Gulfstream Luxury", content: "Gulfstream business jets ($50M-$75M each) generate high margins and consistent cash flow, insulating from defense cycles.", highlight: "High-margin jets", type: "insight" },
        { title: "IT Giant", content: "GDIT provides cloud, cyber, and AI services to U.S. government agencies—a stable, growing $10B+ business.", highlight: "$10B+ IT services", type: "insight" },
        { title: "Competitive Position", content: "Duopoly in subs with Huntington Ingalls. Only Abrams maker. Gulfstream competes with Bombardier/Dassault at top end.", highlight: "Irreplaceable assets", type: "competitive" },
        { title: "Investment Thesis", content: "Most diversified defense name. Gulfstream cycle turning up. Submarine demand locked in. Consistent capital returns. Steady compounder.", highlight: "Diversified compounder", type: "investment" },
      ],
      keyStats: [
        { label: "Revenue (2023)", value: "$42.3B" },
        { label: "Backlog", value: "$93B+" },
        { label: "Gulfstream Deliveries", value: "152" },
      ],
      competitors: ["Huntington Ingalls", "BAE Systems", "Textron"],
    },
    // === SPACE ===
    {
      id: "spacex",
      name: "SpaceX",
      ticker: "Private",
      logo: "🚀",
      logoUrl: LOGOS.spacex,
      segment: "space",
      description: "Space transportation and satellite internet company revolutionizing access to space.",
      industryRole: "SpaceX has disrupted the entire launch industry with reusable rockets. Starlink is creating a new space-based internet infrastructure serving millions.",
      ceo: "Elon Musk",
      founded: "2002",
      headquarters: "Hawthorne, California",
      employees: "13,000+",
      marketCap: "$180B+ (private)",
      keyProducts: ["Falcon 9", "Falcon Heavy", "Starship", "Starlink"],
      recentNews: "Starship development accelerating, Starlink reaching profitability",
      slides: [
        { title: "Launch Revolution", content: "SpaceX launches more payload than all other providers combined. Falcon 9 reusability dropped costs 10x and is approaching 300 flights.", highlight: "300 Falcon 9 flights", type: "insight" },
        { title: "Starship Scale", content: "Starship will be the largest rocket ever flown—capable of 150+ tons to orbit. It's designed for Mars colonization.", highlight: "Mars architecture", type: "insight" },
        { title: "Starlink Empire", content: "6,000+ satellites providing internet to 4M+ subscribers. Revenue run-rate exceeding $10B annually.", highlight: "4M+ subscribers", type: "insight" },
        { title: "Government Anchor", content: "Critical national security asset. NASA relies on Crew Dragon. DoD launching classified payloads. $15B+ government contracts.", highlight: "National asset", type: "insight" },
        { title: "Competitive Position", content: "No competitor can match cadence or price. ULA, Arianespace, Blue Origin years behind. Starship could widen the gap further.", highlight: "Unmatched position", type: "competitive" },
        { title: "Investment Thesis", content: "Only accessible via private markets or Starlink IPO eventually. Transformational company. Valuation reflects dominance. Worth the premium.", highlight: "Generational company", type: "investment" },
      ],
      keyStats: [
        { label: "Launches (2024)", value: "100+" },
        { label: "Starlink Sats", value: "6,000+" },
        { label: "Valuation", value: "$180B+" },
      ],
      competitors: ["Blue Origin", "ULA", "Rocket Lab"],
    },
    {
      id: "blueorigin",
      name: "Blue Origin",
      ticker: "Private",
      logo: "🌍",
      logoUrl: LOGOS.blueorigin,
      segment: "space",
      description: "Space company focused on lowering the cost of space access through reusable rockets.",
      industryRole: "Blue Origin is Jeff Bezos' bet on space infrastructure. New Glenn aims to compete with Falcon 9, while BE-4 engines power key U.S. rockets.",
      ceo: "Dave Limp",
      founded: "2000",
      headquarters: "Kent, Washington",
      employees: "11,000+",
      marketCap: "$30B+ (private)",
      keyProducts: ["New Shepard", "New Glenn", "BE-4 Engine", "Blue Moon Lander"],
      recentNews: "New Glenn first launch imminent, competing for major government contracts",
      slides: [
        { title: "Patient Capital", content: "Bezos has invested $10B+ personally. Blue Origin takes a methodical approach—'Gradatim Ferociter' (step by step, ferociously).", highlight: "$10B+ Bezos investment", type: "insight" },
        { title: "Engine Business", content: "BE-4 engines power both New Glenn and ULA's Vulcan rocket—a rare achievement as engine supplier to a competitor.", highlight: "Powers ULA Vulcan", type: "insight" },
        { title: "Lunar Ambitions", content: "Blue Moon lander selected by NASA for Artemis program. Competing directly with SpaceX for Moon logistics.", highlight: "NASA Artemis partner", type: "insight" },
        { title: "Orbital Wait", content: "New Glenn has been in development since 2012. First orbital flight expected soon, years behind SpaceX.", highlight: "Orbital debut coming", type: "insight" },
        { title: "Competitive Position", content: "Far behind SpaceX but better funded than anyone else. New Glenn must prove reliability. ULA partnership validates engines.", highlight: "Deep pockets", type: "competitive" },
        { title: "Investment Thesis", content: "Private only. Bezos backstop reduces risk. Success depends on New Glenn execution. Long-term infrastructure play.", highlight: "Bezos-backed bet", type: "investment" },
      ],
      keyStats: [
        { label: "New Shepard Flights", value: "25+" },
        { label: "Funding", value: "$10B+" },
        { label: "Employees", value: "11,000+" },
      ],
      competitors: ["SpaceX", "ULA", "Rocket Lab"],
    },
    {
      id: "rocketlab",
      name: "Rocket Lab",
      ticker: "RKLB",
      logo: "🔬",
      logoUrl: LOGOS.rocketlab,
      segment: "space",
      description: "Small satellite launch provider and space systems company.",
      industryRole: "Rocket Lab is the leading dedicated small satellite launcher, with Electron proving reliable access to space for smaller payloads.",
      ceo: "Peter Beck",
      founded: "2006",
      headquarters: "Long Beach, California",
      employees: "2,000+",
      marketCap: "$8B+",
      keyProducts: ["Electron Rocket", "Neutron (development)", "Photon Spacecraft", "Space Components"],
      recentNews: "Neutron medium-lift rocket development accelerating, space systems revenue growing",
      slides: [
        { title: "Small Launch Leader", content: "Electron has flown 50+ times, second only to Falcon 9 in U.S. launch frequency. Dedicated small sat rides to any orbit.", highlight: "50+ Electron flights", type: "insight" },
        { title: "Neutron Bet", content: "Developing Neutron medium-lift rocket to compete with Falcon 9. Designed for mega-constellation deployment.", highlight: "Falcon 9 competitor", type: "insight" },
        { title: "Vertical Integration", content: "Acquired Sinclair Interplanetary and other space component makers. Now builds spacecraft, not just rockets.", highlight: "Space systems", type: "insight" },
        { title: "National Security", content: "Only other U.S. company besides SpaceX with proven rapid launch capability. Critical for responsive space needs.", highlight: "Responsive space", type: "insight" },
        { title: "Competitive Position", content: "Electron owns small launch niche. Neutron must execute against mature Falcon 9. SpaceX remains the benchmark.", highlight: "Niche leader", type: "competitive" },
        { title: "Investment Thesis", content: "Best pure-play space stock. Neutron success determines upside. Space systems provides diversification. High growth, high risk.", highlight: "Pure-play space", type: "investment" },
      ],
      keyStats: [
        { label: "Electron Flights", value: "53" },
        { label: "Revenue (2024)", value: "$430M" },
        { label: "Backlog", value: "$1.1B" },
      ],
      competitors: ["SpaceX", "Firefly", "ABL Space"],
    },
    // === PROPULSION ===
    {
      id: "ge",
      name: "GE Aerospace",
      ticker: "GE",
      logo: "⚙️",
      logoUrl: LOGOS.ge,
      segment: "propulsion",
      description: "World's leading jet engine manufacturer, spun off from General Electric.",
      industryRole: "GE Aerospace (with CFM partner Safran) powers ~75% of all commercial aircraft. The LEAP engine is the industry's bestseller.",
      ceo: "Larry Culp",
      founded: "1917 (GE Aviation)",
      headquarters: "Evendale, Ohio",
      employees: "52,000+",
      marketCap: "$200B+",
      keyProducts: ["LEAP Engine", "GE9X", "GEnx", "CFM56"],
      recentNews: "Spun off from GE conglomerate, pure-play aerospace company",
      slides: [
        { title: "Engine Duopoly", content: "With Pratt & Whitney, GE shares the commercial engine market. CFM (50/50 with Safran) has 75%+ of narrow-body.", highlight: "75% narrow-body", type: "insight" },
        { title: "LEAP Dominance", content: "The LEAP engine powers both 737 MAX and A320neo. Order backlog exceeds 17,000 engines.", highlight: "17,000+ LEAP orders", type: "insight" },
        { title: "Services Moat", content: "Engine aftermarket generates 55% of revenue at 50%+ margins. Long-term service agreements lock in decades of revenue.", highlight: "55% services revenue", type: "insight" },
        { title: "Military Strength", content: "Powers F-15, F-16, F/A-18, and F-35 (with P&W). New NGAD fighter engine competition ongoing.", highlight: "Fighter engines", type: "insight" },
        { title: "Competitive Position", content: "Pratt GTF issues benefit GE/CFM in near term. No new entrant can challenge. Technology lead in efficiency.", highlight: "Tech leader", type: "competitive" },
        { title: "Investment Thesis", content: "Clean aerospace pure-play after spin. Best way to play aviation recovery. Services provide margin stability. Premium warranted.", highlight: "Pure-play leader", type: "investment" },
      ],
      keyStats: [
        { label: "Revenue (2024)", value: "$38B" },
        { label: "Engine Backlog", value: "$150B+" },
        { label: "Installed Base", value: "44,000+" },
      ],
      competitors: ["Pratt & Whitney (RTX)", "Rolls-Royce", "Safran"],
    },
    {
      id: "safran",
      name: "Safran",
      ticker: "SAF.PA",
      logo: "🇫🇷",
      logoUrl: LOGOS.safran,
      segment: "propulsion",
      description: "French aerospace and defense company, major partner in CFM International.",
      industryRole: "Safran is GE's equal partner in CFM, making them critical to 75% of narrow-body aircraft. Also leads in aircraft interiors and landing gear.",
      ceo: "Olivier Andriès",
      founded: "2005 (merger)",
      headquarters: "Paris, France",
      employees: "83,000+",
      marketCap: "$90B+",
      keyProducts: ["CFM LEAP", "Landing Gear", "Nacelles", "Aircraft Interiors"],
      recentNews: "CFM LEAP production ramping to meet unprecedented demand",
      slides: [
        { title: "CFM Partnership", content: "50/50 partner with GE in CFM International since 1974. LEAP engine now powering the world's most popular jets.", highlight: "50/50 with GE", type: "insight" },
        { title: "Landing Gear King", content: "Makes landing gear for 75% of commercial aircraft over 100 seats. Essential, high-margin aftermarket business.", highlight: "75% market share", type: "insight" },
        { title: "Complete Systems", content: "Nacelles, thrust reversers, wiring, interiors—Safran touches almost every part of an aircraft beyond the fuselage.", highlight: "Systems breadth", type: "insight" },
        { title: "Defense Diversification", content: "Helicopter turbines, missile guidance, optronics provide stable defense revenue alongside commercial aviation.", highlight: "Defense balance", type: "insight" },
        { title: "Competitive Position", content: "CFM partnership is irreplaceable. Collins competes in some systems but not engines. European champion status provides political support.", highlight: "Fortress franchise", type: "competitive" },
        { title: "Investment Thesis", content: "Best European aerospace company. CFM provides US exposure without currency risk. Lower valuation than GE for similar business.", highlight: "European pick", type: "investment" },
      ],
      keyStats: [
        { label: "Revenue (2023)", value: "€23.2B" },
        { label: "LEAP Backlog", value: "8,500+" },
        { label: "Employees", value: "83,000+" },
      ],
      competitors: ["Pratt & Whitney", "Collins Aerospace", "Thales"],
    },
    // === SUPPLIERS ===
    {
      id: "honeywell",
      name: "Honeywell Aerospace",
      ticker: "HON",
      logo: "🔧",
      logoUrl: LOGOS.honeywell,
      segment: "suppliers",
      description: "Diversified technology company with major aerospace avionics and engines division.",
      industryRole: "Honeywell Aerospace supplies avionics, engines, and systems to virtually every aircraft program. A critical Tier 1 supplier.",
      ceo: "Vimal Kapur",
      founded: "1906",
      headquarters: "Charlotte, North Carolina",
      employees: "95,000+ (total)",
      marketCap: "$145B+",
      keyProducts: ["Avionics", "Turbine Engines", "APUs", "Connected Aircraft"],
      recentNews: "Aerospace segment driving growth, considering pure-play spin-off",
      slides: [
        { title: "Avionics Powerhouse", content: "Cockpit systems, flight management, weather radar—Honeywell avionics are in 90%+ of commercial aircraft.", highlight: "90%+ presence", type: "insight" },
        { title: "APU Monopoly", content: "Auxiliary Power Units for most large commercial aircraft. High-margin aftermarket business with decades of installed base.", highlight: "APU leader", type: "insight" },
        { title: "Business Aviation", content: "Powers and equips most business jets. HTF7000 engines in popular Gulfstream, Dassault, and Cessna aircraft.", highlight: "Biz jet engines", type: "insight" },
        { title: "Connected Future", content: "Leading the connected aircraft trend with Forge platform, offering predictive maintenance and flight efficiency tools.", highlight: "Digital leader", type: "insight" },
        { title: "Competitive Position", content: "Collins (RTX) is the main competitor. Honeywell's breadth is unmatched. Potential spin-off could unlock value.", highlight: "Spin potential", type: "competitive" },
        { title: "Investment Thesis", content: "Aerospace is crown jewel within conglomerate. Spin-off speculation adds upside. Steady compounder with dividend.", highlight: "Hidden gem", type: "investment" },
      ],
      keyStats: [
        { label: "Aerospace Revenue", value: "$14B" },
        { label: "Installed Base", value: "100,000+ aircraft" },
        { label: "Aftermarket %", value: "50%+" },
      ],
      competitors: ["Collins Aerospace", "Thales", "L3Harris"],
    },
    {
      id: "transdigm",
      name: "TransDigm",
      ticker: "TDG",
      logo: "🔩",
      logoUrl: LOGOS.transdigm,
      segment: "suppliers",
      description: "Aerospace components company known for niche, proprietary products and pricing power.",
      industryRole: "TransDigm owns sole-source positions on thousands of aircraft components. Their business model focuses on acquiring proprietary parts with high aftermarket value.",
      ceo: "Kevin Stein",
      founded: "1993",
      headquarters: "Cleveland, Ohio",
      employees: "22,000+",
      marketCap: "$75B+",
      keyProducts: ["Mechanical/Electro-Mechanical Actuators", "Ignition Systems", "Gear Pumps", "Lighting"],
      recentNews: "Continued M&A strategy, strong aftermarket pricing",
      slides: [
        { title: "Niche Strategy", content: "TransDigm owns 80%+ sole-source positions on its products. Once designed into aircraft, they're nearly impossible to replace.", highlight: "80%+ sole-source", type: "insight" },
        { title: "Pricing Power", content: "Notorious for aggressive aftermarket pricing—parts needed to keep aircraft flying. DOD has investigated but business model persists.", highlight: "Pricing power", type: "insight" },
        { title: "M&A Machine", content: "Acquires aerospace component companies, applies operational improvements, and leverages pricing. 100+ acquisitions completed.", highlight: "100+ acquisitions", type: "insight" },
        { title: "EBITDA Focus", content: "50%+ EBITDA margins—among the highest in aerospace. Private equity DNA with public market scale.", highlight: "50%+ EBITDA margins", type: "insight" },
        { title: "Competitive Position", content: "No direct competitor replicates the model. Regulatory scrutiny is the risk. Moat deepens with each acquisition.", highlight: "Unique model", type: "competitive" },
        { title: "Investment Thesis", content: "Controversial but successful. Best returns in aerospace over 20 years. Premium valuation but premium business. Not for ESG investors.", highlight: "Return champion", type: "investment" },
      ],
      keyStats: [
        { label: "Revenue (2024)", value: "$7.9B" },
        { label: "EBITDA Margin", value: "52%" },
        { label: "Acquisitions", value: "100+" },
      ],
      competitors: ["HEICO", "Parker Hannifin", "Moog"],
    },
    {
      id: "heico",
      name: "HEICO",
      ticker: "HEI",
      logo: "✨",
      logoUrl: LOGOS.heico,
      segment: "suppliers",
      description: "Aerospace and electronics company specializing in aftermarket parts and components.",
      industryRole: "HEICO is the largest independent supplier of FAA-approved replacement parts. They offer OEM alternatives at lower cost.",
      ceo: "Laurans Mendelson",
      founded: "1957",
      headquarters: "Hollywood, Florida",
      employees: "9,000+",
      marketCap: "$32B+",
      keyProducts: ["PMA Parts", "Electronic Components", "Repair Services"],
      recentNews: "Strong growth in PMA parts as airlines seek cost savings",
      slides: [
        { title: "PMA Pioneer", content: "Parts Manufacturer Approval (PMA) parts are FAA-certified alternatives to OEM parts, often 30-50% cheaper.", highlight: "30-50% savings", type: "insight" },
        { title: "Family Legacy", content: "Mendelson family has run HEICO for 30+ years with remarkable discipline. Known for patient capital allocation.", highlight: "Family-run", type: "insight" },
        { title: "Electronics Segment", content: "Flight Support Group makes aerospace parts; Electronic Technologies makes mission-critical components for defense.", highlight: "Dual segments", type: "insight" },
        { title: "M&A Excellence", content: "Acquired 95+ companies with a decentralized model that preserves entrepreneurial culture. No hostile deals.", highlight: "95+ acquisitions", type: "insight" },
        { title: "Competitive Position", content: "OEMs dislike PMA but can't stop it. TransDigm is larger but different model. Airlines are natural allies.", highlight: "Airlines ally", type: "competitive" },
        { title: "Investment Thesis", content: "Exceptional long-term compounder. Premium valuation for premium culture. Low volatility growth. Hold forever.", highlight: "Forever stock", type: "investment" },
      ],
      keyStats: [
        { label: "Revenue (2024)", value: "$3.9B" },
        { label: "Operating Margin", value: "22%+" },
        { label: "Acquisitions", value: "95+" },
      ],
      competitors: ["TransDigm", "AAR Corp", "Parts OEMs"],
    },
  ],
  neuroscience: [
    // === BRAIN-COMPUTER INTERFACES ===
    {
      id: "neuralink",
      name: "Neuralink",
      logo: "🧠",
      logoUrl: LOGOS.neuralink,
      segment: "devices",
      description: "Elon Musk's brain-computer interface company developing high-bandwidth implantable devices.",
      industryRole: "Neuralink is attempting to revolutionize BCIs with a high-channel-count implant and robotic surgery. They're pushing the boundaries of what's possible in neural interfaces.",
      ceo: "Elon Musk",
      founded: "2016",
      headquarters: "Fremont, California",
      employees: "400+",
      keyProducts: ["N1 Implant", "R1 Surgical Robot", "Neural Threads"],
      recentNews: "First human patient received implant in 2024, showing promise for paralysis treatment",
      slides: [
        { title: "High-Bandwidth Vision", content: "Neuralink's N1 chip has 1,024 electrodes—10x more than competitors. Goal: restore communication and mobility for paralyzed patients.", highlight: "1,024 electrodes", type: "insight" },
        { title: "Robotic Surgery", content: "The R1 robot can implant 64 threads with micron precision, potentially enabling outpatient brain surgery in the future.", highlight: "Robotic precision", type: "insight" },
        { title: "First Human Trial", content: "Noland Arbaugh became the first patient in 2024, demonstrating thought-controlled cursor movement and gaming.", highlight: "Human trial started", type: "insight" },
        { title: "Ambitious Roadmap", content: "Long-term vision includes memory enhancement, AI symbiosis, and treating neurological conditions. Highly speculative but well-funded.", highlight: "Moonshot ambitions", type: "insight" },
        { title: "Competitive Position", content: "Better funded than competitors but faces regulatory hurdles. Synchron has FDA approval advantage. BCI market still nascent.", highlight: "Well-funded challenger", type: "competitive" },
        { title: "Investment Thesis", content: "Private company. Watch for IPO potential. High risk, transformative upside. Dependent on Musk's execution and FDA pathway.", highlight: "Private, high-risk", type: "investment" },
      ],
      keyStats: [
        { label: "Funding Raised", value: "$680M+" },
        { label: "Electrode Count", value: "1,024" },
        { label: "First Patient", value: "2024" },
      ],
      competitors: ["Synchron", "Blackrock Neurotech", "Paradromics"],
    },
    {
      id: "synchron",
      name: "Synchron",
      logo: "🔗",
      logoUrl: LOGOS.synchron,
      segment: "devices",
      description: "Minimally invasive brain-computer interface company with FDA breakthrough designation.",
      industryRole: "Synchron's Stentrode is implanted via blood vessels, avoiding open brain surgery. They're leading the 'less invasive' BCI approach.",
      ceo: "Tom Oxley",
      founded: "2012",
      headquarters: "Brooklyn, New York",
      employees: "150+",
      keyProducts: ["Stentrode", "Motor Neuroprosthesis", "BCI Platform"],
      recentNews: "FDA Breakthrough Device designation, multiple U.S. patients implanted",
      slides: [
        { title: "Vascular Approach", content: "The Stentrode is implanted through the jugular vein, eliminating need for open brain surgery. 10-minute procedure vs hours for competitors.", highlight: "No open surgery", type: "insight" },
        { title: "FDA Lead", content: "First company to receive FDA IDE approval for permanent BCI implant. Multiple U.S. patients already implanted and using the device.", highlight: "FDA-approved trials", type: "insight" },
        { title: "ALS Focus", content: "Initially targeting ALS patients who lose ability to speak. Restoring digital communication is life-changing for this population.", highlight: "ALS patients first", type: "insight" },
        { title: "Hospital-Friendly", content: "Interventional neurologists can implant Stentrode with existing skills. No special training required. Scalable.", highlight: "Easy implantation", type: "insight" },
        { title: "Competitive Position", content: "Less electrodes than Neuralink but safer procedure. First-mover in regulatory approval. Lower-risk approach may win long-term.", highlight: "Safety advantage", type: "competitive" },
        { title: "Investment Thesis", content: "Private company. Strategic interest from Gates, Bezos, DARPA. Lower technical risk than competitors. Watch for commercial launch.", highlight: "Strategic backing", type: "investment" },
      ],
      keyStats: [
        { label: "Funding Raised", value: "$145M+" },
        { label: "FDA Status", value: "Breakthrough" },
        { label: "Procedure Time", value: "~10 min" },
      ],
      competitors: ["Neuralink", "Blackrock Neurotech", "Precision Neuroscience"],
    },
    {
      id: "blackrock",
      name: "Blackrock Neurotech",
      logo: "⚡",
      logoUrl: LOGOS.blackrock,
      segment: "devices",
      description: "Pioneer in brain-computer interfaces with 20+ years of human implant experience.",
      industryRole: "Blackrock's Utah Array has been implanted in more humans than any other BCI. They're the established leader in research-grade neural interfaces.",
      ceo: "Marcus Gerhardt",
      founded: "2008",
      headquarters: "Salt Lake City, Utah",
      employees: "100+",
      keyProducts: ["Utah Array", "NeuroPort", "MoveAgain BCI"],
      recentNews: "MoveAgain BCI system advancing toward commercial FDA approval",
      slides: [
        { title: "BCI Pioneer", content: "The Utah Array has been implanted in 40+ humans over 20 years. More real-world BCI experience than any competitor.", highlight: "40+ human implants", type: "insight" },
        { title: "Research Standard", content: "Used in landmark studies at Brown, Stanford, and other top institutions. Published science validates the technology.", highlight: "Research gold standard", type: "insight" },
        { title: "MoveAgain System", content: "Commercial BCI for paralysis patients. Enables control of computers, phones, and wheelchairs through thought.", highlight: "Commercial BCI", type: "insight" },
        { title: "Acquisition Target", content: "Deep IP portfolio and regulatory experience make Blackrock attractive to pharma and tech giants entering neurotech.", highlight: "Strategic asset", type: "insight" },
        { title: "Competitive Position", content: "Most proven but older technology. Neuralink threatens with better specs. Synchron with easier procedure. Must innovate or partner.", highlight: "Proven but aging", type: "competitive" },
        { title: "Investment Thesis", content: "Private company. Underappreciated pioneer. Strategic M&A likely. Lower risk than Neuralink, more upside than established medtech.", highlight: "M&A candidate", type: "investment" },
      ],
      keyStats: [
        { label: "Human Implants", value: "40+" },
        { label: "Years Experience", value: "20+" },
        { label: "Research Papers", value: "500+" },
      ],
      competitors: ["Neuralink", "Synchron", "Paradromics"],
    },
    // === DIGITAL THERAPEUTICS ===
    {
      id: "pear",
      name: "Pear Therapeutics",
      logo: "🍐",
      logoUrl: LOGOS.pear,
      segment: "therapeutics",
      description: "Pioneer in FDA-cleared prescription digital therapeutics for mental health.",
      industryRole: "Pear created the first FDA-cleared prescription digital therapeutic (PDT). They're defining how software can be prescribed like medicine.",
      ceo: "Corey McCann (former)",
      founded: "2013",
      headquarters: "Boston, Massachusetts",
      employees: "200+",
      keyProducts: ["reSET", "reSET-O", "Somryst"],
      recentNews: "Filed for bankruptcy in 2023—cautionary tale for DTx sector",
      slides: [
        { title: "DTx Pioneer", content: "reSET was the first FDA-cleared prescription app for substance use disorder. Proved software could be regulated medicine.", highlight: "First FDA PDT", type: "insight" },
        { title: "Three Products", content: "reSET (addiction), reSET-O (opioid use), and Somryst (insomnia) showed clinical efficacy in randomized trials.", highlight: "Clinical validation", type: "insight" },
        { title: "Reimbursement Challenge", content: "Despite FDA approval, payers resisted coverage. CPT codes and formulary placement remained barriers.", highlight: "Payer resistance", type: "insight" },
        { title: "Bankruptcy Lesson", content: "2023 bankruptcy despite $300M+ raised. Lesson: FDA approval doesn't guarantee commercial success in digital health.", highlight: "Cautionary tale", type: "insight" },
        { title: "Competitive Position", content: "Assets sold to various acquirers. Model validated clinically but business model failed. Sector recalibrating expectations.", highlight: "Assets dispersed", type: "competitive" },
        { title: "Investment Thesis", content: "Company failed but validated the PDT category. Watch acquirers like Click Therapeutics and Better Therapeutics building on lessons.", highlight: "Category validated", type: "investment" },
      ],
      keyStats: [
        { label: "FDA Clearances", value: "3" },
        { label: "Funding Raised", value: "$300M+" },
        { label: "Status", value: "Bankrupt 2023" },
      ],
      competitors: ["Akili", "Better Therapeutics", "Click Therapeutics"],
    },
    // === PSYCHEDELIC MEDICINE ===
    {
      id: "compass",
      name: "COMPASS Pathways",
      ticker: "CMPS",
      logo: "🧭",
      logoUrl: LOGOS.compass,
      segment: "therapeutics",
      description: "Leading psilocybin therapy development for treatment-resistant depression.",
      industryRole: "COMPASS is furthest along in developing psilocybin as an FDA-approved medicine. They're defining the regulatory pathway for psychedelic therapeutics.",
      ceo: "Kabir Nath",
      founded: "2016",
      headquarters: "London, UK",
      employees: "200+",
      marketCap: "$500M+",
      keyProducts: ["COMP360 Psilocybin", "Therapy Protocol", "Digital Support"],
      recentNews: "Phase 3 trials ongoing for treatment-resistant depression",
      slides: [
        { title: "Psilocybin Leader", content: "COMP360 is synthetic psilocybin in Phase 3 trials for depression. FDA Breakthrough Therapy designation accelerates path.", highlight: "Breakthrough status", type: "insight" },
        { title: "Treatment-Resistant Focus", content: "30% of depression patients don't respond to existing meds. COMP360 targets this underserved population with single-dose treatment.", highlight: "30% unmet need", type: "insight" },
        { title: "Therapy Protocol", content: "Not just a drug—includes trained therapists and specialized treatment centers. Service component critical to outcomes.", highlight: "Drug + therapy", type: "insight" },
        { title: "IP Strategy", content: "Extensive patent portfolio on synthesis, formulation, and treatment protocols. Building moat beyond molecule.", highlight: "IP moat building", type: "insight" },
        { title: "Competitive Position", content: "Leads in psilocybin but MDMA (Lykos) may reach market first. Regulatory and stigma risks remain. First-mover matters.", highlight: "Psilocybin leader", type: "competitive" },
        { title: "Investment Thesis", content: "High-risk, high-reward. Phase 3 readout critical. Addressable market huge if approved. Binary regulatory outcome.", highlight: "Binary bet", type: "investment" },
      ],
      keyStats: [
        { label: "Clinical Stage", value: "Phase 3" },
        { label: "Cash Position", value: "$200M+" },
        { label: "Patents Filed", value: "50+" },
      ],
      competitors: ["Lykos (MDMA)", "atai Life Sciences", "Cybin"],
    },
    {
      id: "atai",
      name: "atai Life Sciences",
      ticker: "ATAI",
      logo: "🔬",
      logoUrl: LOGOS.atai,
      segment: "therapeutics",
      description: "Biotech platform developing psychedelic and non-psychedelic mental health treatments.",
      industryRole: "atai takes a portfolio approach to psychedelic medicine, investing in multiple compounds and companies to diversify risk in an uncertain regulatory landscape.",
      ceo: "Florian Brand",
      founded: "2018",
      headquarters: "Berlin, Germany",
      employees: "150+",
      marketCap: "$300M+",
      keyProducts: ["PCN-101 (R-ketamine)", "DMT Program", "Portfolio Companies"],
      recentNews: "Advancing multiple programs including R-ketamine for depression",
      slides: [
        { title: "Platform Model", content: "atai owns stakes in 15+ psychedelic companies, diversifying across psilocybin, ketamine, DMT, and novel compounds.", highlight: "15+ portfolio cos", type: "insight" },
        { title: "R-Ketamine Lead", content: "PCN-101 is a cleaner version of ketamine with potentially fewer side effects. Phase 2 data promising.", highlight: "Better ketamine", type: "insight" },
        { title: "Venture Builder", content: "Incubates and acquires early-stage psychedelic companies, providing capital, infrastructure, and expertise.", highlight: "Venture model", type: "insight" },
        { title: "Big Pharma Interest", content: "Partnered with Otsuka on DMT research. Traditional pharma increasingly interested in psychedelic mechanisms.", highlight: "Otsuka partner", type: "insight" },
        { title: "Competitive Position", content: "Diversified vs focused competitors. More shots on goal but diluted ownership. Macro sentiment affects all psychedelic stocks.", highlight: "Diversified risk", type: "competitive" },
        { title: "Investment Thesis", content: "Basket approach to psychedelic investing. Lower binary risk but less focused. Watch for platform value inflection.", highlight: "Portfolio play", type: "investment" },
      ],
      keyStats: [
        { label: "Portfolio Companies", value: "15+" },
        { label: "Cash Position", value: "$250M+" },
        { label: "Lead Program", value: "Phase 2" },
      ],
      competitors: ["COMPASS Pathways", "Cybin", "Mind Medicine"],
    },
    // === BIG PHARMA NEURO ===
    {
      id: "biogen",
      name: "Biogen",
      ticker: "BIIB",
      logo: "🧬",
      logoUrl: LOGOS.biogen,
      segment: "pharma",
      description: "Biotechnology pioneer focused on neurological diseases including Alzheimer's and MS.",
      industryRole: "Biogen pioneered MS treatment and is at the forefront of the controversial but potentially transformative Alzheimer's drug market.",
      ceo: "Chris Viehbacher",
      founded: "1978",
      headquarters: "Cambridge, Massachusetts",
      employees: "7,500+",
      marketCap: "$25B+",
      keyProducts: ["Leqembi (Alzheimer's)", "Tysabri", "Spinraza", "Tecfidera"],
      recentNews: "Leqembi gaining traction as first disease-modifying Alzheimer's treatment",
      slides: [
        { title: "Neuro Pioneer", content: "Biogen built the MS treatment market and is now defining the emerging Alzheimer's disease-modifying therapy category.", highlight: "MS & Alzheimer's", type: "insight" },
        { title: "Leqembi Launch", content: "Co-developed with Eisai, Leqembi is the first Alzheimer's drug to show clear amyloid plaque reduction and cognitive benefit.", highlight: "Disease-modifying", type: "insight" },
        { title: "MS Franchise", content: "Tysabri and oral therapies generate $5B+ annually. Facing biosimilar pressure but still highly profitable.", highlight: "$5B MS franchise", type: "insight" },
        { title: "Spinraza Success", content: "Gene therapy for spinal muscular atrophy was a breakthrough, though facing competition from Novartis's Zolgensma.", highlight: "SMA breakthrough", type: "insight" },
        { title: "Competitive Position", content: "Leqembi faces Eli Lilly's Kisunla. MS portfolio eroding to generics. Must execute Alzheimer's launch and pipeline.", highlight: "Execution critical", type: "competitive" },
        { title: "Investment Thesis", content: "Turnaround dependent on Alzheimer's adoption. Undervalued if Leqembi scales. High-risk, potential multi-bagger.", highlight: "Alzheimer's bet", type: "investment" },
      ],
      keyStats: [
        { label: "Revenue (2023)", value: "$9.8B" },
        { label: "R&D Spend", value: "$2.5B" },
        { label: "Pipeline Programs", value: "30+" },
      ],
      competitors: ["Eli Lilly", "Roche", "AbbVie"],
    },
    {
      id: "lilly",
      name: "Eli Lilly",
      ticker: "LLY",
      logo: "💊",
      logoUrl: LOGOS.lilly,
      segment: "pharma",
      description: "Global pharmaceutical company with major investments in Alzheimer's and neuroscience.",
      industryRole: "Lilly is betting heavily on Alzheimer's with donanemab (Kisunla), competing directly with Biogen's Leqembi for the disease-modifying therapy market.",
      ceo: "David Ricks",
      founded: "1876",
      headquarters: "Indianapolis, Indiana",
      employees: "43,000+",
      marketCap: "$750B+",
      keyProducts: ["Kisunla (Alzheimer's)", "Mounjaro", "Verzenio", "Taltz"],
      recentNews: "Kisunla FDA-approved, competing with Leqembi for Alzheimer's market",
      slides: [
        { title: "Pharma Giant", content: "Lilly's market cap exceeded $750B driven by Mounjaro/Zepbound obesity drugs. Massive cash generation funds neuro R&D.", highlight: "$750B+ valuation", type: "insight" },
        { title: "Kisunla Launch", content: "Donanemab (Kisunla) approved for Alzheimer's in 2024. Different dosing regimen than Leqembi may offer convenience.", highlight: "Alzheimer's entry", type: "insight" },
        { title: "Neuro Pipeline", content: "Beyond Alzheimer's: pain, migraine, and neurodegenerative disease programs. Deep commitment to CNS.", highlight: "Deep CNS pipeline", type: "insight" },
        { title: "Manufacturing Power", content: "Investing $10B+ in manufacturing to meet demand for obesity and Alzheimer's drugs. Supply is competitive advantage.", highlight: "$10B+ capex", type: "insight" },
        { title: "Competitive Position", content: "Kisunla vs Leqembi battle will define Alzheimer's market. Lilly's resources and execution track record favor them.", highlight: "Best resourced", type: "competitive" },
        { title: "Investment Thesis", content: "Premium valuation justified by obesity franchise. Alzheimer's is optionality. Core holding for pharma exposure.", highlight: "Quality compounder", type: "investment" },
      ],
      keyStats: [
        { label: "Market Cap", value: "$750B+" },
        { label: "Revenue (2023)", value: "$34B" },
        { label: "R&D Spend", value: "$9B+" },
      ],
      competitors: ["Biogen", "Roche", "Novo Nordisk"],
    },
    // === NEURODEVICES ===
    {
      id: "medtronic",
      name: "Medtronic",
      ticker: "MDT",
      logo: "💓",
      logoUrl: LOGOS.medtronic,
      segment: "devices",
      description: "World's largest medical device company with leading deep brain stimulation technology.",
      industryRole: "Medtronic's DBS systems are the gold standard for treating Parkinson's, essential tremor, and epilepsy. They define the neuromodulation device market.",
      ceo: "Geoffrey Martha",
      founded: "1949",
      headquarters: "Dublin, Ireland",
      employees: "95,000+",
      marketCap: "$110B+",
      keyProducts: ["DBS Systems", "Percept PC", "SenSight Leads", "Spine Stimulators"],
      recentNews: "Percept PC with BrainSense technology enables personalized Parkinson's treatment",
      slides: [
        { title: "DBS Pioneer", content: "Medtronic invented deep brain stimulation for movement disorders. 200,000+ patients treated with DBS globally.", highlight: "200K+ DBS patients", type: "insight" },
        { title: "BrainSense Tech", content: "Percept PC records brain signals while stimulating, enabling adaptive therapy that responds to patient state.", highlight: "Adaptive therapy", type: "insight" },
        { title: "Neuromod Leader", content: "Beyond DBS: spinal cord stimulators for pain, sacral neuromodulation for bladder, and emerging applications.", highlight: "Full neuromod suite", type: "insight" },
        { title: "Clinical Evidence", content: "Decades of clinical data, physician training, and established reimbursement create strong competitive moat.", highlight: "Evidence moat", type: "insight" },
        { title: "Competitive Position", content: "Abbott and Boston Scientific compete in neuromod. Medtronic leads in DBS but facing innovation pressure.", highlight: "Market leader", type: "competitive" },
        { title: "Investment Thesis", content: "Diversified medtech giant. Neuro is 10% of revenue. Low-growth but stable. Dividend aristocrat.", highlight: "Steady compounder", type: "investment" },
      ],
      keyStats: [
        { label: "Revenue (2023)", value: "$31B" },
        { label: "DBS Patients", value: "200,000+" },
        { label: "Dividend Yield", value: "~3%" },
      ],
      competitors: ["Abbott", "Boston Scientific", "LivaNova"],
    },
    {
      id: "abbott",
      name: "Abbott Neuromodulation",
      ticker: "ABT",
      logo: "🔋",
      logoUrl: LOGOS.abbott,
      segment: "devices",
      description: "Diversified healthcare company with growing neuromodulation and DBS business.",
      industryRole: "Abbott's St. Jude acquisition brought DBS and spinal cord stimulation expertise. They're the fastest-growing competitor to Medtronic in neuromod.",
      ceo: "Robert Ford",
      founded: "1888",
      headquarters: "Abbott Park, Illinois",
      employees: "115,000+",
      marketCap: "$190B+",
      keyProducts: ["Infinity DBS", "Proclaim XR", "NeuroSphere", "Eterna SCS"],
      recentNews: "Infinity DBS system gaining share with directional stimulation technology",
      slides: [
        { title: "DBS Challenger", content: "Abbott's Infinity DBS with directional leads offers more precise stimulation, taking share from Medtronic.", highlight: "Directional leads", type: "insight" },
        { title: "Pain Management", content: "Proclaim spinal cord stimulators and dorsal root ganglion therapy address chronic pain market.", highlight: "SCS portfolio", type: "insight" },
        { title: "Digital Platform", content: "NeuroSphere Virtual Clinic enables remote programming, increasingly important post-COVID.", highlight: "Remote capability", type: "insight" },
        { title: "Diversified Parent", content: "Neuromod is ~5% of Abbott revenue. Backed by diagnostics and nutrition cash flows.", highlight: "Strong parent", type: "insight" },
        { title: "Competitive Position", content: "Gaining share vs Medtronic in DBS. Boston Scientific strong in SCS. Three-way competition intensifying.", highlight: "Share gains", type: "competitive" },
        { title: "Investment Thesis", content: "Neuromod is growth driver within diversified Abbott. Lower pure-play exposure but reduced risk. Buy the diversified platform.", highlight: "Diversified play", type: "investment" },
      ],
      keyStats: [
        { label: "Abbott Revenue", value: "$40B+" },
        { label: "Neuromod Share", value: "~5%" },
        { label: "Market Cap", value: "$190B+" },
      ],
      competitors: ["Medtronic", "Boston Scientific", "Nevro"],
    },
  ],
  
  // AI & Machine Learning Key Players
  ai: [
    {
      id: "openai",
      name: "OpenAI",
      logo: "🤖",
      logoUrl: getLogoUrl("openai.com"),
      segment: "commercial",
      description: "Leading AI research company behind ChatGPT, GPT-4, and DALL-E.",
      industryRole: "OpenAI pioneered large language models and conversational AI, setting the standard for generative AI applications.",
      ceo: "Sam Altman",
      founded: "2015",
      headquarters: "San Francisco, CA",
      employees: "1,500+",
      marketCap: "$86B+ (valuation)",
      keyProducts: ["ChatGPT", "GPT-4", "DALL-E 3", "Whisper", "Sora"],
      slides: [
        { title: "AI Pioneer", content: "OpenAI's ChatGPT reached 100M users in 2 months—the fastest-growing consumer app in history. They defined the LLM era.", highlight: "100M users in 2 months", type: "insight" },
        { title: "Enterprise Play", content: "ChatGPT Enterprise targets businesses with enhanced security, longer context, and GPT-4 access. 80% of Fortune 500 use ChatGPT.", highlight: "80% Fortune 500", type: "insight" },
        { title: "Microsoft Alliance", content: "Microsoft invested $13B for 49% stake. Azure hosts OpenAI models exclusively, giving both massive competitive advantage.", highlight: "$13B from Microsoft", type: "insight" },
        { title: "Competitive Position", content: "Leads in model capability but Google (Gemini) and Anthropic (Claude) closing gap. Open-source (Llama, Mistral) threatens moat.", highlight: "Capability leader", type: "competitive" },
        { title: "Investment Thesis", content: "Category leader with massive distribution. Revenue run rate $2B+. Risks: compute costs, competition, safety concerns, Microsoft dependency.", highlight: "Category king", type: "investment" },
      ],
      competitors: ["Google DeepMind", "Anthropic", "Meta AI"],
    },
    {
      id: "anthropic",
      name: "Anthropic",
      logo: "🧠",
      logoUrl: getLogoUrl("anthropic.com"),
      segment: "commercial",
      description: "AI safety company developing Claude, focused on reliable and steerable AI systems.",
      industryRole: "Founded by ex-OpenAI researchers, Anthropic leads in AI alignment research and constitutional AI approaches.",
      ceo: "Dario Amodei",
      founded: "2021",
      headquarters: "San Francisco, CA",
      employees: "500+",
      marketCap: "$18B+ (valuation)",
      keyProducts: ["Claude 3.5 Sonnet", "Claude Enterprise", "Constitutional AI"],
      slides: [
        { title: "Safety-First AI", content: "Anthropic pioneered Constitutional AI—training models to be helpful, harmless, and honest through principles rather than RLHF.", highlight: "Constitutional AI", type: "insight" },
        { title: "Claude Performance", content: "Claude 3.5 Sonnet matches or beats GPT-4 on many benchmarks while being faster and cheaper. 200K context window.", highlight: "200K context", type: "insight" },
        { title: "Amazon Partnership", content: "Amazon invested up to $4B for minority stake. Claude available on AWS Bedrock, challenging Microsoft-OpenAI alliance.", highlight: "$4B from Amazon", type: "insight" },
        { title: "Competitive Position", content: "Best technical alternative to OpenAI. Strong enterprise traction. Differentiated on safety narrative. Claude preferred for coding.", highlight: "Safety leader", type: "competitive" },
        { title: "Investment Thesis", content: "Premium positioning in AI safety. Strong enterprise adoption. Key risk: compute costs and whether safety focus becomes competitive advantage.", highlight: "Safety moat", type: "investment" },
      ],
      competitors: ["OpenAI", "Google DeepMind", "Cohere"],
    },
    {
      id: "nvidia",
      name: "NVIDIA",
      ticker: "NVDA",
      logo: "💚",
      logoUrl: getLogoUrl("nvidia.com"),
      segment: "commercial",
      description: "The dominant AI chip company powering the entire machine learning revolution.",
      industryRole: "NVIDIA's GPUs are essential for training and running AI models. They control 80%+ of the AI accelerator market.",
      ceo: "Jensen Huang",
      founded: "1993",
      headquarters: "Santa Clara, CA",
      employees: "29,000+",
      marketCap: "$3T+",
      keyProducts: ["H100 GPU", "A100 GPU", "CUDA", "DGX Systems", "Blackwell"],
      slides: [
        { title: "AI Picks & Shovels", content: "Every major AI lab runs on NVIDIA GPUs. Data centers can't buy H100s fast enough—12-month backlogs common.", highlight: "12-month backlog", type: "insight" },
        { title: "CUDA Moat", content: "CUDA software ecosystem locks in developers. 4M+ developers, decades of libraries. Switching costs are immense.", highlight: "4M+ developers", type: "insight" },
        { title: "Data Center Dominance", content: "Data center revenue grew 409% YoY. Now 80%+ of revenue vs. gaming. Complete pivot to AI.", highlight: "409% YoY growth", type: "insight" },
        { title: "Competitive Position", content: "Near-monopoly in AI training. AMD (MI300) and Intel (Gaudi) years behind. Custom chips (Google TPU) only threat.", highlight: "Training monopoly", type: "competitive" },
        { title: "Investment Thesis", content: "Best AI exposure. Pricing power intact. Risks: customer building own chips, competition catching up, demand normalization.", highlight: "AI infrastructure", type: "investment" },
      ],
      competitors: ["AMD", "Intel", "Google TPU"],
    },
    {
      id: "google-deepmind",
      name: "Google DeepMind",
      logo: "🔮",
      logoUrl: getLogoUrl("deepmind.com"),
      segment: "commercial",
      description: "Google's AI research lab combining DeepMind and Google Brain, creators of Gemini.",
      industryRole: "DeepMind leads fundamental AI research (AlphaFold, AlphaGo) while powering Google's AI products with Gemini.",
      ceo: "Demis Hassabis",
      founded: "2010",
      headquarters: "London, UK",
      employees: "3,000+",
      keyProducts: ["Gemini", "AlphaFold", "Bard", "Google AI Studio"],
      slides: [
        { title: "Research Powerhouse", content: "AlphaFold solved 50-year protein folding problem. AlphaGo beat world Go champion. Fundamental AI breakthroughs.", highlight: "AlphaFold breakthrough", type: "insight" },
        { title: "Gemini Launch", content: "Gemini Ultra matches GPT-4 on benchmarks. 1M token context. Natively multimodal—trained on text, images, audio, video together.", highlight: "1M token context", type: "insight" },
        { title: "Google Integration", content: "Gemini powers Search, Workspace, Cloud, Android. Massive distribution through Google's 4B+ user products.", highlight: "4B+ users", type: "insight" },
        { title: "Competitive Position", content: "Google has data, compute, and distribution. Gemini competitive but playing catch-up to ChatGPT mindshare.", highlight: "Distribution advantage", type: "competitive" },
        { title: "Investment Thesis", content: "Access via Alphabet (GOOGL). AI upside underpriced vs. core search business. Key risk: search disruption by AI.", highlight: "Undervalued AI", type: "investment" },
      ],
      competitors: ["OpenAI", "Anthropic", "Meta AI"],
    },
  ],
  
  // Fintech Key Players
  fintech: [
    {
      id: "stripe",
      name: "Stripe",
      logo: "💳",
      logoUrl: getLogoUrl("stripe.com"),
      segment: "commercial",
      description: "The leading online payments infrastructure company powering internet commerce.",
      industryRole: "Stripe is the default payment stack for startups and increasingly enterprises. They process hundreds of billions annually.",
      ceo: "Patrick Collison",
      founded: "2010",
      headquarters: "San Francisco, CA",
      employees: "8,000+",
      marketCap: "$65B (valuation)",
      keyProducts: ["Stripe Payments", "Stripe Connect", "Stripe Atlas", "Stripe Billing"],
      slides: [
        { title: "Internet's Payment Rails", content: "Stripe processes $817B+ annually. Used by Amazon, Google, Shopify, and millions of startups. 3.1M+ websites.", highlight: "$817B processed", type: "insight" },
        { title: "Developer First", content: "Famous for developer experience. A few lines of code to accept payments. This drove massive bottom-up adoption.", highlight: "Developer beloved", type: "insight" },
        { title: "Platform Play", content: "Stripe Connect enables marketplaces (Lyft, DoorDash) to pay out. Stripe Atlas helps start companies. Full-stack fintech.", highlight: "Full-stack fintech", type: "insight" },
        { title: "Competitive Position", content: "Dominant with startups, growing with enterprises. Adyen and PayPal compete at top. Moat is developer ecosystem.", highlight: "Startup dominant", type: "competitive" },
        { title: "Investment Thesis", content: "Private but expected to IPO. Take rate ~2.9%. Trades on processed volume growth. Key risk: fee compression, enterprise competition.", highlight: "IPO candidate", type: "investment" },
      ],
      competitors: ["Adyen", "PayPal", "Square"],
    },
    {
      id: "plaid",
      name: "Plaid",
      logo: "🔗",
      logoUrl: getLogoUrl("plaid.com"),
      segment: "commercial",
      description: "The leading financial data connectivity platform linking apps to bank accounts.",
      industryRole: "Plaid connects 12,000+ apps to banks, enabling account verification, payments, and data aggregation for fintechs.",
      ceo: "Zach Perret",
      founded: "2013",
      headquarters: "San Francisco, CA",
      employees: "1,500+",
      marketCap: "$13B (valuation)",
      keyProducts: ["Plaid Link", "Plaid Transactions", "Plaid Identity", "Plaid Income"],
      slides: [
        { title: "Financial Plumbing", content: "Plaid connects to 12,000+ financial institutions. 1 in 3 Americans with bank accounts have connected via Plaid.", highlight: "1 in 3 Americans", type: "insight" },
        { title: "Network Effects", content: "More apps using Plaid means better bank connections. More bank connections attracts more apps. Classic platform flywheel.", highlight: "Platform flywheel", type: "insight" },
        { title: "Visa Block", content: "Visa tried to acquire for $5.3B but DOJ blocked on antitrust. Plaid now independent and expanding globally.", highlight: "DOJ blocked Visa", type: "insight" },
        { title: "Competitive Position", content: "Dominant in US. MX, Yodlee, Finicity compete. Open banking regulations help and hurt—enable competition but expand market.", highlight: "US dominant", type: "competitive" },
        { title: "Investment Thesis", content: "Private, likely IPO. Every fintech needs data connectivity. Key risks: open banking standardization, big bank direct APIs.", highlight: "Essential infrastructure", type: "investment" },
      ],
      competitors: ["MX", "Yodlee", "Finicity"],
    },
    {
      id: "nubank",
      name: "Nubank",
      ticker: "NU",
      logo: "💜",
      logoUrl: getLogoUrl("nubank.com.br"),
      segment: "commercial",
      description: "Latin America's largest digital bank with 90M+ customers across Brazil, Mexico, and Colombia.",
      industryRole: "Nubank proved digital banks can achieve massive scale in emerging markets, disrupting legacy banks with mobile-first approach.",
      ceo: "David Vélez",
      founded: "2013",
      headquarters: "São Paulo, Brazil",
      employees: "8,000+",
      marketCap: "$60B+",
      keyProducts: ["Nu Credit Card", "NuAccount", "NuInvest", "Nu Loans"],
      slides: [
        { title: "LatAm Giant", content: "90M+ customers across Brazil, Mexico, Colombia. Brazil's 5th largest financial institution by customers.", highlight: "90M+ customers", type: "insight" },
        { title: "Unit Economics", content: "Achieved profitability with $10+ monthly ARPAC. CAC under $5. Most efficient customer acquisition in banking.", highlight: "$5 CAC", type: "insight" },
        { title: "Product Expansion", content: "Started with credit cards, now offers accounts, investing, loans, insurance. Full banking stack, 100% mobile.", highlight: "Full banking stack", type: "insight" },
        { title: "Competitive Position", content: "Dominant in Brazil neobanking. Inter, C6 compete locally. Expanding to Mexico as next growth driver.", highlight: "Brazil dominant", type: "competitive" },
        { title: "Investment Thesis", content: "Best emerging market fintech play. Profitable and growing. FX risk from BRL. Mexico scaling is key catalyst.", highlight: "EM fintech leader", type: "investment" },
      ],
      competitors: ["Inter", "C6 Bank", "Mercado Pago"],
    },
  ],
  
  // Biotech Key Players  
  biotech: [
    {
      id: "moderna",
      name: "Moderna",
      ticker: "MRNA",
      logo: "💉",
      logoUrl: getLogoUrl("modernatx.com"),
      segment: "therapeutics",
      description: "mRNA therapeutics pioneer that developed COVID-19 vaccine and expanding into oncology, rare diseases.",
      industryRole: "Moderna proved mRNA platform works at scale. Now applying it to flu, RSV, cancer, and rare genetic diseases.",
      ceo: "Stéphane Bancel",
      founded: "2010",
      headquarters: "Cambridge, MA",
      employees: "5,000+",
      marketCap: "$40B+",
      keyProducts: ["Spikevax (COVID)", "mRNA Flu Vaccine", "Oncology Pipeline", "Rare Disease Programs"],
      slides: [
        { title: "mRNA Pioneer", content: "Moderna's COVID vaccine validated mRNA platform—$18B+ peak revenue. Technology now proven for rapid vaccine development.", highlight: "$18B peak revenue", type: "insight" },
        { title: "Platform Power", content: "mRNA is a platform, not one product. Same manufacturing for any protein. Flu, RSV, CMV, cancer vaccines in pipeline.", highlight: "Platform approach", type: "insight" },
        { title: "Oncology Expansion", content: "Personalized cancer vaccines in Phase 3 with Merck. Trains immune system to attack specific tumor mutations.", highlight: "Cancer vaccines", type: "insight" },
        { title: "Competitive Position", content: "Platform leader alongside BioNTech. Big Pharma (Pfizer, Sanofi) licensing mRNA. Key question: post-COVID sustainability.", highlight: "Platform leader", type: "competitive" },
        { title: "Investment Thesis", content: "Post-COVID decline priced in. Pipeline optionality undervalued. Key risks: clinical trial failures, competition, variant uncertainty.", highlight: "Pipeline optionality", type: "investment" },
      ],
      competitors: ["BioNTech", "Pfizer", "CureVac"],
    },
    {
      id: "regeneron",
      name: "Regeneron",
      ticker: "REGN",
      logo: "🧬",
      logoUrl: getLogoUrl("regeneron.com"),
      segment: "therapeutics",
      description: "Biotechnology leader in antibody drugs for eye disease, cancer, inflammation, and infectious disease.",
      industryRole: "Regeneron's VelocImmune platform generates fully human antibodies faster than competitors. Scientific excellence drives innovation.",
      ceo: "Leonard Schleifer",
      founded: "1988",
      headquarters: "Tarrytown, NY",
      employees: "12,000+",
      marketCap: "$100B+",
      keyProducts: ["Eylea", "Dupixent", "Libtayo", "REGEN-COV"],
      slides: [
        { title: "Antibody Excellence", content: "VelocImmune platform generates human antibodies in mice. Produced blockbusters Eylea ($6B+) and Dupixent ($11B+).", highlight: "$11B+ Dupixent", type: "insight" },
        { title: "Sanofi Partnership", content: "Dupixent partnership with Sanofi generated $11B+ in 2023. Treats eczema, asthma, COPD—expanding indications.", highlight: "Sanofi partnership", type: "insight" },
        { title: "Obesity Entry", content: "Partnered with Sanofi on obesity drug. Late entrant but Regeneron's track record commands respect.", highlight: "Obesity play", type: "insight" },
        { title: "Competitive Position", content: "Best antibody platform. Eylea faces biosimilar pressure. Dupixent growth offsets. Pipeline quality high.", highlight: "Platform strength", type: "competitive" },
        { title: "Investment Thesis", content: "Quality compounder. Dupixent growth + obesity optionality. Eylea headwinds known. Premium valuation deserved.", highlight: "Quality biotech", type: "investment" },
      ],
      competitors: ["Amgen", "Genentech", "AbbVie"],
    },
  ],
};

export const defaultCompanies: Company[] = [
  {
    id: "default",
    name: "Coming Soon",
    logo: "🔜",
    segment: "commercial",
    description: "More key players will be added to this market soon.",
    industryRole: "Check back soon for detailed industry analysis.",
    ceo: "TBD",
    founded: "N/A",
    headquarters: "Various",
    employees: "N/A",
    keyProducts: [],
    slides: [
      { title: "Coming Soon", content: "We're adding more companies to this market. Stay tuned!", type: "insight" },
    ],
  },
];
