// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/list-markets.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.91.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-markets.ts
var list_markets_default = defineTool({
  name: "list_markets",
  title: "List markets",
  description: "List the industry markets available in MarketLingo (id, name, description) so other tools can be called with a valid market id.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("markets").select("id, name, description").order("name");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { markets: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-my-progress.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
var get_my_progress_default = defineTool2({
  name: "get_my_progress",
  title: "Get my learning progress",
  description: "Get the signed-in learner's MarketLingo snapshot: selected market, current day of the 180-day track, streak, learning goal, familiarity level, XP and level.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const userId = ctx.getUserId();
    const supabase = supabaseForUser(ctx);
    const { data: profile, error: profileError } = await supabase.from("profiles").select("username, selected_market, familiarity_level, is_pro_user").eq("id", userId).maybeSingle();
    if (profileError) {
      return { content: [{ type: "text", text: profileError.message }], isError: true };
    }
    const marketId = profile?.selected_market ?? null;
    const [{ data: progress }, { data: xp }] = await Promise.all([
      marketId ? supabase.from("user_progress").select("market_id, current_day, current_streak, longest_streak, learning_goal, familiarity_level, last_activity_at, completed_stacks").eq("user_id", userId).eq("market_id", marketId).maybeSingle() : Promise.resolve({ data: null }),
      marketId ? supabase.from("user_xp").select("total_xp, current_level, xp_to_next_level").eq("user_id", userId).eq("market_id", marketId).maybeSingle() : Promise.resolve({ data: null })
    ]);
    const snapshot = {
      username: profile?.username ?? null,
      market_id: marketId,
      is_pro_user: profile?.is_pro_user ?? false,
      current_day: progress?.current_day ?? null,
      current_streak: progress?.current_streak ?? 0,
      longest_streak: progress?.longest_streak ?? 0,
      learning_goal: progress?.learning_goal ?? null,
      familiarity_level: progress?.familiarity_level ?? profile?.familiarity_level ?? null,
      last_activity_at: progress?.last_activity_at ?? null,
      completed_stacks_count: (progress?.completed_stacks ?? []).length,
      total_xp: xp?.total_xp ?? 0,
      current_level: xp?.current_level ?? 1,
      xp_to_next_level: xp?.xp_to_next_level ?? null
    };
    return {
      content: [{ type: "text", text: JSON.stringify(snapshot) }],
      structuredContent: snapshot
    };
  }
});

// src/lib/mcp/tools/list-lessons.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";
var list_lessons_default = defineTool3({
  name: "list_lessons",
  title: "List lessons",
  description: "Browse published MarketLingo lesson stacks for a market. Optionally filter by title keyword or stack type (for example lesson, news, drill).",
  inputSchema: {
    market_id: z.string().trim().min(1).describe("Market id from list_markets, e.g. 'ai'."),
    search: z.string().trim().min(1).optional().describe("Optional keyword to match in the lesson title."),
    stack_type: z.string().trim().min(1).optional().describe("Optional stack type filter."),
    limit: z.number().int().min(1).max(50).optional().describe("Max lessons to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ market_id, search, stack_type, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("stacks").select("id, market_id, title, stack_type, duration_minutes, tags, published_at").eq("market_id", market_id).order("published_at", { ascending: false, nullsFirst: false }).limit(limit ?? 20);
    if (search) query = query.ilike("title", `%${search}%`);
    if (stack_type) query = query.eq("stack_type", stack_type);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data?.length) {
      return { content: [{ type: "text", text: `No lessons found for market "${market_id}".` }] };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { lessons: data }
    };
  }
});

// src/lib/mcp/tools/get-drills.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var get_drills_default = defineTool4({
  name: "get_drills",
  title: "Get practice drills",
  description: "Fetch true/false practice drill questions for a market, optionally for a specific day of the 180-day track, including the explanation for each statement.",
  inputSchema: {
    market_id: z2.string().trim().min(1).describe("Market id from list_markets."),
    day_number: z2.number().int().min(1).max(365).optional().describe("Optional day of the track."),
    limit: z2.number().int().min(1).max(30).optional().describe("Max questions to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ market_id, day_number, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("drill_questions").select("id, market_id, day_number, set_number, question_number, statement, is_true, explanation, category, difficulty").eq("market_id", market_id).order("day_number", { ascending: true }).order("question_number", { ascending: true }).limit(limit ?? 10);
    if (day_number !== void 0) query = query.eq("day_number", day_number);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data?.length) {
      return { content: [{ type: "text", text: `No drills found for market "${market_id}".` }] };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { drills: data }
    };
  }
});

// src/lib/mcp/tools/list-my-notes.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var list_my_notes_default = defineTool5({
  name: "list_my_notes",
  title: "List my notes",
  description: "List the signed-in learner's saved MarketLingo notebook entries, newest first, with an optional keyword search and market filter.",
  inputSchema: {
    search: z3.string().trim().min(1).optional().describe("Optional keyword to match in note content."),
    market_id: z3.string().trim().min(1).optional().describe("Optional market id filter."),
    limit: z3.number().int().min(1).max(100).optional().describe("Max notes to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, market_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("notes").select("id, content, linked_label, market_id, stack_id, created_at, updated_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 25);
    if (search) query = query.ilike("content", `%${search}%`);
    if (market_id) query = query.eq("market_id", market_id);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data?.length) {
      return { content: [{ type: "text", text: "No notes found." }], structuredContent: { notes: [] } };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { notes: data }
    };
  }
});

// src/lib/mcp/tools/create-note.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.25.76";
var create_note_default = defineTool6({
  name: "create_note",
  title: "Create a note",
  description: "Save a note to the signed-in learner's MarketLingo notebook, optionally tagged to a market and given a short label.",
  inputSchema: {
    content: z4.string().trim().min(1).max(5e3).describe("The note text to save."),
    market_id: z4.string().trim().min(1).optional().describe("Optional market id to file the note under."),
    linked_label: z4.string().trim().min(1).max(120).optional().describe("Optional short label or topic for the note.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ content, market_id, linked_label }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("notes").insert({
      user_id: ctx.getUserId(),
      content,
      market_id: market_id ?? null,
      linked_label: linked_label ?? null
    }).select("id, content, linked_label, market_id, created_at").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Note saved: ${JSON.stringify(data)}` }],
      structuredContent: { note: data }
    };
  }
});

// src/lib/mcp/tools/delete-note.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z5 } from "npm:zod@^3.25.76";
var delete_note_default = defineTool7({
  name: "delete_note",
  title: "Delete a note",
  description: "Permanently delete one of the signed-in learner's MarketLingo notebook entries by its id.",
  inputSchema: {
    note_id: z5.string().uuid().describe("Id of the note to delete, from list_my_notes.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ note_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("notes").delete().eq("id", note_id).eq("user_id", ctx.getUserId()).select("id");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data?.length) {
      return { content: [{ type: "text", text: "No note with that id belongs to you." }], isError: true };
    }
    return {
      content: [{ type: "text", text: `Deleted note ${note_id}.` }],
      structuredContent: { deleted_id: note_id }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "wahrcgvzarcgmktjleyr";
var mcp_default = defineMcp({
  name: "marketlingo",
  title: "MarketLingo",
  version: "0.1.0",
  instructions: "Tools for MarketLingo, an industry-fluency learning app. Call list_markets first to resolve a market id, get_my_progress for the signed-in learner's track, streak and XP, list_lessons and get_drills to browse study content, and list_my_notes / create_note / delete_note to manage their notebook. All tools act as the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_markets_default,
    get_my_progress_default,
    list_lessons_default,
    get_drills_default,
    list_my_notes_default,
    create_note_default,
    delete_note_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
